#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate
python manage.py add_pipeline
exec uvicorn config.asgi:application --host 0.0.0.0 --reload --reload-include '*.html'
