# Generated by Django 4.2.10 on 2024-08-23 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("main", "0036_event_calculated_fields_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxonObserved",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("detections_count", models.IntegerField(default=0)),
                ("occurrences_count", models.IntegerField(default=0)),
                ("best_determination_score", models.FloatField(blank=True, null=True)),
                ("last_detected", models.DateTimeField(blank=True, null=True)),
                ("calculated_fields_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "best_detection",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="main.detection"
                    ),
                ),
                ("detections", models.ManyToManyField(related_name="taxa_observed", to="main.detection")),
                ("occurrences", models.ManyToManyField(related_name="taxa_observed", to="main.occurrence")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="taxa_observed", to="main.project"
                    ),
                ),
                (
                    "taxon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="observations", to="main.taxon"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Taxa Observed",
                "ordering": ["-last_detected"],
            },
        ),
    ]
