# Generated by Django 4.2.2 on 2023-07-06 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deployment",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="deployments"),
        ),
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="projects"),
        ),
        migrations.AlterField(
            model_name="classification",
            name="determination",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classifications",
                to="main.taxon",
            ),
        ),
    ]
