# Generated by Django 4.2.5 on 2023-09-22 01:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_remove_identification_unique_primary_identification_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="identification",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveConstraint(
            model_name="identification",
            name="unique_primary_identification",
        ),
        migrations.RemoveField(
            model_name="identification",
            name="primary",
        ),
        migrations.RemoveField(
            model_name="identification",
            name="priority",
        ),
        migrations.AddField(
            model_name="identification",
            name="withdrawn",
            field=models.BooleanField(default=False),
        ),
    ]
