# Generated by Django 4.2.5 on 2023-09-22 18:06

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_identification_options_and_more"),
    ]

    operations = [TrigramExtension()]
