# Generated by Django 4.2.2 on 2023-07-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="progress",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
