# Generated by Django 4.2.5 on 2023-09-26 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_identification_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="identification",
            name="agreed_with_identification",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="main.identification"
            ),
        ),
        migrations.AddField(
            model_name="identification",
            name="agreed_with_prediction",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="main.classification"
            ),
        ),
    ]
