# Generated by Django 4.2.5 on 2023-09-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_search_extensions"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxon",
            name="display_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, unique=True, verbose_name="Cached display name"
            ),
        ),
    ]
