# Generated by Django 4.2.2 on 2023-07-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_job_config_alter_job_progress"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sourceimage",
            options={"ordering": ("deployment", "event", "timestamp")},
        ),
        migrations.AlterField(
            model_name="job",
            name="config",
            field=models.JSONField(
                default={
                    "input": {"name": "Captures", "size": 100},
                    "stages": [
                        {
                            "key": "object_detection",
                            "name": "Object Detection",
                            "params": [
                                {"key": "model", "name": "Localization Model", "value": "yolov5s"},
                                {"key": "batch_size", "name": "Batch size", "value": 8},
                                {"key": "input_size", "name": "Images processed", "read_only": True},
                                {"key": "output_size", "name": "Objects detected", "read_only": True},
                            ],
                        },
                        {
                            "key": "binary_classification",
                            "name": "Objects of Interest Filter",
                            "params": [
                                {"key": "algorithm", "name": "Binary classification model", "value": "resnet18"},
                                {"key": "batch_size", "name": "Batch size", "value": 8},
                                {"key": "input_size", "name": "Objects processed", "read_only": True},
                                {"key": "output_size", "name": "Objects of interest", "read_only": True},
                            ],
                        },
                        {
                            "key": "species_classification",
                            "name": "Species Classification",
                            "params": [
                                {"key": "algorithm", "name": "Species classification model", "value": "resnet18"},
                                {"key": "batch_size", "name": "Batch size", "value": 8},
                                {"key": "threshold", "name": "Confidence threshold", "value": 0.5},
                                {"key": "input_size", "name": "Species processed", "read_only": True},
                                {"key": "output_size", "name": "Species classified", "read_only": True},
                            ],
                        },
                        {
                            "key": "tracking",
                            "name": "Occurrence Tracking",
                            "params": [
                                {"key": "algorithm", "name": "Occurrence tracking algorithm", "value": "adityacombo"},
                                {"key": "input_size", "name": "Detections processed", "read_only": True},
                                {"key": "output_size", "name": "Occurrences identified", "read_only": True},
                            ],
                        },
                    ],
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="progress",
            field=models.JSONField(
                default={
                    "stages": [
                        {
                            "input_size": 0,
                            "key": "object_detection",
                            "output_size": 0,
                            "progress": 0,
                            "status": "PENDING",
                            "status_label": "0% completed.",
                            "time_elapsed": 0,
                            "time_remaining": None,
                        },
                        {
                            "input_size": 0,
                            "key": "binary_classification",
                            "output_size": 0,
                            "progress": 0,
                            "status": "PENDING",
                            "status_label": "0% completed.",
                            "time_elapsed": 0,
                            "time_remaining": None,
                        },
                        {
                            "input_size": 0,
                            "key": "species_classification",
                            "output_size": 0,
                            "progress": 0,
                            "status": "PENDING",
                            "status_label": "0% completed.",
                            "time_elapsed": 0,
                            "time_remaining": None,
                        },
                        {
                            "input_size": 0,
                            "key": "tracking",
                            "output_size": 0,
                            "progress": 0,
                            "status": "PENDING",
                            "time_elapsed": 0,
                            "time_remaining": None,
                        },
                    ],
                    "summary": {"progress": 0, "status": "PENDING", "status_label": "0% completed."},
                },
                null=True,
            ),
        ),
    ]
