# Generated by Django 4.2.2 on 2023-09-26 23:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_identification_agreed_with_identification_and_more"),
        ("main", "0005_taxon_display_name"),
    ]

    operations = []
