# Generated by Django 4.2.2 on 2023-07-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_alter_sourceimage_options_alter_job_config_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taxalist",
            options={"ordering": ["-created_at"], "verbose_name_plural": "Taxa Lists"},
        ),
        migrations.AlterModelOptions(
            name="taxon",
            options={"ordering": ["parent__name", "ordering", "name"], "verbose_name_plural": "Taxa"},
        ),
        migrations.AddField(
            model_name="taxon",
            name="authorship_date",
            field=models.DateField(blank=True, help_text="The date the taxon was described.", null=True),
        ),
        migrations.AddField(
            model_name="taxon",
            name="ordering",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="taxalist",
            name="taxa",
        ),
        migrations.DeleteModel(
            name="TaxaListEntry",
        ),
    ]
