# Generated by Django 4.2.2 on 2023-10-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_merge_20230926_2353"),
    ]

    operations = [
        migrations.AddField(
            model_name="deployment",
            name="data_source_inventory",
            field=models.FileField(blank=True, null=True, upload_to="source_image_inventories"),
        ),
    ]
