# Generated by Django 4.2.2 on 2023-10-12 02:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_deployment_data_source_inventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="deployment",
            name="assumed_image_height",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deployment",
            name="assumed_image_width",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
