# Generated by Django 4.2.2 on 2023-10-12 03:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_sourceimageupload"),
        ("main", "0008_deployment_assumed_image_height_and_more"),
    ]

    operations = []
