# Generated by Django 4.2.2 on 2023-10-16 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_rename_capture_sourceimageupload_source_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourceimageupload",
            name="source_image",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="main.sourceimage"
            ),
        ),
    ]
