# Generated by Django 4.2.2 on 2023-10-17 02:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_alter_sourceimageupload_source_image"),
        ("main", "0009_merge_20231012_0304"),
    ]

    operations = []
