# Generated by Django 4.2.2 on 2023-10-20 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_alter_sourceimageupload_source_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourceimagecollection",
            name="kwargs",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Arguments passed to the sampling function (JSON dict)",
                null=True,
                verbose_name="Arguments",
            ),
        ),
        migrations.AlterField(
            model_name="sourceimagecollection",
            name="method",
            field=models.CharField(
                choices=[
                    ("random", "random"),
                    ("stratified_random", "stratified_random"),
                    ("interval", "interval"),
                    ("manual", "manual"),
                    ("random_from_each_event", "random_from_each_event"),
                    ("last_and_random_from_each_event", "last_and_random_from_each_event"),
                    ("greatest_file_size_from_each_event", "greatest_file_size_from_each_event"),
                    ("detections_only", "detections_only"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="sourceimageupload",
            name="source_image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="upload",
                to="main.sourceimage",
            ),
        ),
    ]
