# Generated by Django 4.2.2 on 2023-10-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_taxon_author_taxon_bold_taxon_bin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxon",
            name="rank",
            field=models.CharField(
                choices=[
                    ("ORDER", "Order"),
                    ("SUPERFAMILY", "Superfamily"),
                    ("FAMILY", "Family"),
                    ("SUBFAMILY", "Subfamily"),
                    ("TRIBE", "Tribe"),
                    ("SUBTRIBE", "Subtribe"),
                    ("GENUS", "Genus"),
                    ("SPECIES", "Species"),
                ],
                default="SPECIES",
                max_length=255,
            ),
        ),
    ]
