# Generated by Django 4.2.2 on 2023-10-31 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_alter_taxon_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourceimage",
            name="detections_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
