# Generated by Django 4.2.2 on 2023-08-15 19:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_remove_sourceimage_md5hash_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StorageSource",
        ),
        migrations.RenameField(
            model_name="deployment",
            old_name="data_source",
            new_name="data_source_old",
        ),
        migrations.RemoveField(
            model_name="deployment",
            name="data_source_last_checked",
        ),
    ]
