# Generated by Django 4.2.2 on 2023-11-01 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_sourceimage_detections_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="source_image_collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="main.sourceimagecollection",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="source_image_single",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="main.sourceimage",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="task_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="taxon",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="direct_children",
                to="main.taxon",
            ),
        ),
    ]
