# Generated by Django 4.2.2 on 2023-08-15 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_delete_storagesource_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="S3StorageSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("bucket", models.CharField(max_length=255)),
                ("prefix", models.CharField(blank=True, max_length=255)),
                ("access_key", models.TextField()),
                ("secret_key", models.TextField()),
                ("endpoint_url", models.CharField(blank=True, max_length=255, null=True)),
                ("public_base_url", models.CharField(blank=True, max_length=255)),
                ("total_size", models.IntegerField(blank=True, null=True)),
                ("total_files", models.IntegerField(blank=True, null=True)),
                ("last_checked", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="deployment",
            name="data_source_old",
        ),
        migrations.AddField(
            model_name="deployment",
            name="data_source",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="main.s3storagesource"
            ),
        ),
    ]
