# Generated by Django 4.2.2 on 2023-11-02 00:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_job_source_image_collection_job_source_image_single_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Job",
        ),
    ]
