# Generated by Django 4.2.2 on 2023-11-02 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0015_delete_job"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pipeline",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("version", models.CharField(blank=True, max_length=255)),
                ("stages", models.JSONField(blank=True, null=True)),
                ("algorithms", models.ManyToManyField(related_name="pipelines", to="main.algorithm")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
