# Generated by Django 4.2.2 on 2023-08-15 19:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0015_s3storagesource_remove_deployment_data_source_old_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sourceimage",
            name="md5hash",
        ),
    ]
