# Generated by Django 4.2.2 on 2023-11-23 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0016_pipeline"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="site",
            options={"verbose_name": "Research Site"},
        ),
        migrations.AddField(
            model_name="site",
            name="project",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sites", to="main.project"
            ),
        ),
    ]
