# Generated by Django 4.2.2 on 2023-11-09 23:17

from django.db import migrations, models
import django.db.models.deletion


def remove_existing_pipelines_and_algorithms(apps, schema_editor):
    Pipeline = apps.get_model("ml", "Pipeline")
    Pipeline.objects.all().delete()

    Algorithm = apps.get_model("ml", "Algorithm")
    Algorithm.objects.all().delete()


def backwards_no_problem(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0008_alter_job_pipeline"),
        ("ml", "0001_initial"),
        ("main", "0016_pipeline"),
    ]

    operations = [
        migrations.RunPython(remove_existing_pipelines_and_algorithms, backwards_no_problem),
        migrations.RemoveField(
            model_name="pipeline",
            name="algorithms",
        ),
        migrations.AlterField(
            model_name="classification",
            name="algorithm",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="ml.algorithm"),
        ),
        migrations.AlterField(
            model_name="detection",
            name="detection_algorithm",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="ml.algorithm"
            ),
        ),
        migrations.DeleteModel(
            name="Algorithm",
        ),
        migrations.DeleteModel(
            name="Pipeline",
        ),
    ]
