# Generated by Django 4.2.2 on 2023-08-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0016_remove_sourceimage_md5hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="s3storagesource",
            name="total_files",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="s3storagesource",
            name="total_size",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
