# Generated by Django 4.2.2 on 2023-11-10 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0001_initial"),
        ("main", "0017_remove_pipeline_algorithms"),
        ("jobs", "0008_alter_job_pipeline"),
    ]

    operations = [
        migrations.RunSQL(
            "DELETE FROM main_classification WHERE algorithm_id NOT IN (SELECT id FROM ml_algorithm)", ""
        ),
    ]
