# Generated by Django 4.2.2 on 2023-08-17 22:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0017_alter_s3storagesource_total_files_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sourceimage",
            old_name="source",
            new_name="public_url",
        ),
    ]
