# Generated by Django 4.2.2 on 2023-11-10 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0001_initial"),
        ("main", "0018_delete_existing_pipeline_algorithms"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Pipeline",
        ),
        migrations.RemoveField(
            model_name="detection",
            name="detection_algorithm",
        ),
        migrations.AlterField(
            model_name="classification",
            name="algorithm",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="ml.algorithm"),
        ),
        migrations.DeleteModel(
            name="Algorithm",
        ),
    ]
