# Generated by Django 4.2.2 on 2023-11-23 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0018_device_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="s3storagesource",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="storage_sources",
                to="main.project",
            ),
        ),
    ]
