# Generated by Django 4.2.2 on 2023-11-10 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0001_initial"),
        ("main", "0019_delete_pipeline_remove_detection_detection_algorithm_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="detection",
            name="detection_algorithm",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="ml.algorithm"
            ),
        ),
    ]
