# Generated by Django 4.2.2 on 2023-08-18 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0019_rename_public_url_sourceimage_public_base_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="deployment",
            name="data_source_regex",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="deployment",
            name="data_source_subdir",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="deployment",
            name="data_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deployments",
                to="main.s3storagesource",
            ),
        ),
    ]
