# Generated by Django 4.2.2 on 2023-11-23 03:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0019_s3storagesource_project"),
        ("main", "0020_detection_detection_algorithm"),
    ]

    operations = []
