# Generated by Django 4.2.2 on 2023-08-18 01:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0020_deployment_data_source_regex_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deployment",
            name="data_source_last_checked",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deployment",
            name="data_source_size",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
