# Generated by Django 4.2.2 on 2023-11-29 23:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0021_merge_20231123_0307"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourceimagecollection",
            name="method",
            field=models.CharField(
                choices=[
                    ("random", "random"),
                    ("stratified_random", "stratified_random"),
                    ("interval", "interval"),
                    ("manual", "manual"),
                    ("starred", "starred"),
                    ("random_from_each_event", "random_from_each_event"),
                    ("last_and_random_from_each_event", "last_and_random_from_each_event"),
                    ("greatest_file_size_from_each_event", "greatest_file_size_from_each_event"),
                    ("detections_only", "detections_only"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="taxon",
            name="rank",
            field=models.CharField(
                choices=[
                    ("ORDER", "Order"),
                    ("SUPERFAMILY", "Superfamily"),
                    ("FAMILY", "Family"),
                    ("SUBFAMILY", "Subfamily"),
                    ("TRIBE", "Tribe"),
                    ("SUBTRIBE", "Subtribe"),
                    ("GENUS", "Genus"),
                    ("SPECIES", "Species"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="SPECIES",
                max_length=255,
            ),
        ),
    ]
