# Generated by Django 4.2.2 on 2023-11-29 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0022_alter_sourceimagecollection_method_alter_taxon_rank"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="taxon",
            index=models.Index(fields=["ordering", "name"], name="main_taxon_orderin_4ffb7b_idx"),
        ),
    ]
