# Generated by Django 4.2.2 on 2023-08-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0022_alter_sourceimage_size"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="sourceimage",
            constraint=models.UniqueConstraint(fields=("deployment", "path"), name="unique_deployment_path"),
        ),
        migrations.AddConstraint(
            model_name="sourceimage",
            constraint=models.UniqueConstraint(fields=("deployment", "timestamp"), name="unique_deployment_timestamp"),
        ),
    ]
