# Generated by Django 4.2.2 on 2023-12-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0023_taxon_main_taxon_orderin_4ffb7b_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="deployment",
            name="captures_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deployment",
            name="detections_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deployment",
            name="events_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deployment",
            name="first_capture_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deployment",
            name="last_capture_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deployment",
            name="occurrences_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deployment",
            name="taxa_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
