# Generated by Django 4.2.2 on 2023-08-20 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0023_sourceimage_unique_deployment_path_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["start"]},
        ),
        migrations.AddField(
            model_name="event",
            name="group_by",
            field=models.CharField(
                db_index=True,
                default=datetime.date(2023, 8, 20),
                help_text="A unique identifier for this event, used to group images into events. This allows images to be prepended or appended to an existing event. The recommended value is the day the event started, in the format YYYY-MM-DD.",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="end",
            field=models.DateTimeField(
                blank=True, help_text="The timestamp of the last image in the event.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="start",
            field=models.DateTimeField(
                db_index=True, help_text="The timestamp of the first image in the event.", 
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["group_by", "start"], name="main_event_group_b_3b75c6_idx"),
        ),
    ]
