# Generated by Django 4.2.2 on 2023-12-01 21:43

from django.db import migrations
import logging

logger = logging.getLogger(__name__)


# Save all Deployment objects to update their calculated fields.
def update_deployment_aggregates(apps, schema_editor):
    Deployment = apps.get_model("main", "Deployment")
    # from ami.main.models import Deployment

    for deployment in Deployment.objects.all():
        logger.info(f"Updating deployment {deployment}")
        # deployment.save(update_calculated_fields=True)
        deployment.save()


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0024_deployment_captures_count_and_more"),
    ]

    # operations = []
    operations = [
        migrations.RunPython(update_deployment_aggregates, migrations.RunPython.noop),
    ]
