# Generated by Django 4.2.2 on 2023-08-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0025_remove_event_main_event_group_b_3b75c6_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deployment",
            name="data_source_size",
        ),
        migrations.AlterField(
            model_name="event",
            name="group_by",
            field=models.CharField(
                db_index=True,
                help_text="A unique identifier for this event, used to group images into events. This allows images to be prepended or appended to an existing event. The default value is the day the event started, in the format YYYY-MM-DD. However images could also be grouped by camera settings, image dimensions, hour of day, or a random sample.",
                max_length=255,
            ),
        ),
    ]
