# Generated by Django 4.2.2 on 2023-12-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0025_update_deployment_aggregates"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrence",
            name="determination_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
