# Generated by Django 4.2.2 on 2023-12-02 01:08

from django.db import migrations


# Call save on all occurrences to update their scores
def update_occurrence_scores(apps, schema_editor):
    # Occurrence = apps.get_model("main", "Occurrence")
    from ami.main.models import Occurrence

    for occurrence in Occurrence.objects.all():
        occurrence.save()


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0026_occurrence_determination_score"),
    ]

    operations = [
        migrations.RunPython(update_occurrence_scores, migrations.RunPython.noop),
    ]
