# Generated by Django 4.2.2 on 2023-08-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0026_remove_deployment_data_source_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deployment",
            name="data_source_total_files",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deployment",
            name="data_source_total_size",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
