# Generated by Django 4.2.2 on 2023-12-11 02:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0027_update_occurrence_scores"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="occurrence",
            options={"ordering": ["-determination_score"]},
        ),
    ]
