# Generated by Django 4.2.2 on 2024-02-02 23:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0028_alter_occurrence_options"),
        ("main", "0028_alter_occurrence_options_alter_project_options_and_more"),
    ]

    operations = []
