# Generated by Django 4.2.2 on 2024-04-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0030_identification_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="s3storagesource",
            name="use_presigned_urls",
            field=models.BooleanField(
                default=True, help_text="Uncheck this option if your image URLs are public for faster loading."
            ),
        ),
        migrations.AlterField(
            model_name="sourceimagecollection",
            name="method",
            field=models.CharField(
                choices=[
                    ("common_combined", "common_combined"),
                    ("random", "random"),
                    ("stratified_random", "stratified_random"),
                    ("interval", "interval"),
                    ("manual", "manual"),
                    ("starred", "starred"),
                    ("random_from_each_event", "random_from_each_event"),
                    ("last_and_random_from_each_event", "last_and_random_from_each_event"),
                    ("greatest_file_size_from_each_event", "greatest_file_size_from_each_event"),
                    ("detections_only", "detections_only"),
                ],
                default="common_combined",
                max_length=255,
            ),
        ),
    ]
