# Generated by Django 4.2.2 on 2024-05-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0031_s3storagesource_use_presigned_urls_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="s3storagesource",
            name="public_base_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
