# Generated by Django 4.2.2 on 2023-09-08 02:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0031_event_project_sourceimage_project_taxalist_projects_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deployment",
            options={"ordering": ["name"]},
        ),
    ]
