# Generated by Django 4.2.2 on 2023-09-13 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0032_alter_deployment_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Identification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("primary", models.BooleanField(default=False)),
                ("priority", models.IntegerField(default=1)),
                (
                    "occurrence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identifications",
                        to="main.occurrence",
                    ),
                ),
                (
                    "taxon",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="identifications",
                        to="main.taxon",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="identifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="identification",
            constraint=models.UniqueConstraint(fields=("occurrence", "primary"), name="unique_primary_identification"),
        ),
    ]
