# Generated by Django 4.2.10 on 2024-08-05 19:42

import ami.main.models
from django.db import migrations
import django_pydantic_field._migration_serializers
import django_pydantic_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0033_remove_s3storagesource_use_presigned_urls_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taxon",
            name="parents",
        ),
        migrations.AddField(
            model_name="taxon",
            name="parents_json",
            field=django_pydantic_field.fields.PydanticSchemaField(
                blank=True,
                config=None,
                null=True,
                schema=django_pydantic_field._migration_serializers.GenericContainer(
                    list, (ami.main.models.TaxonParent,)
                ),
            ),
        ),
    ]
