# Generated by Django 4.2.2 on 2023-09-14 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0033_identification_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="classification",
            old_name="determination",
            new_name="taxon",
        ),
        migrations.AddField(
            model_name="classification",
            name="occurrence",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="predictions",
                to="main.occurrence",
            ),
        ),
    ]
