# Generated by Django 4.2.10 on 2024-08-06 17:47

import ami.main.models
from django.db import migrations, models
import django_pydantic_field._migration_serializers
import django_pydantic_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0034_remove_taxon_parents_taxon_parents_json"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxon",
            name="parents_json",
            field=django_pydantic_field.fields.PydanticSchemaField(
                blank=True,
                config=None,
                default=list,
                schema=django_pydantic_field._migration_serializers.GenericContainer(
                    list, (ami.main.models.TaxonParent,)
                ),
            ),
        ),
        migrations.AlterField(
            model_name="taxon",
            name="rank",
            field=models.CharField(
                choices=[
                    ("ORDER", "ORDER"),
                    ("SUPERFAMILY", "SUPERFAMILY"),
                    ("FAMILY", "FAMILY"),
                    ("SUBFAMILY", "SUBFAMILY"),
                    ("TRIBE", "TRIBE"),
                    ("SUBTRIBE", "SUBTRIBE"),
                    ("GENUS", "GENUS"),
                    ("SPECIES", "SPECIES"),
                    ("UNKNOWN", "UNKNOWN"),
                ],
                default="SPECIES",
                max_length=255,
            ),
        ),
    ]
