# Generated by Django 4.2.2 on 2023-09-14 00:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0034_rename_determination_classification_taxon_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="classification",
            name="main_classification_type_valid",
        ),
        migrations.RemoveField(
            model_name="classification",
            name="type",
        ),
    ]
