# Generated by Django 4.2.2 on 2023-09-14 00:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0035_remove_classification_main_classification_type_valid_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="classification",
            options={"ordering": ["-score"]},
        ),
        migrations.RemoveField(
            model_name="classification",
            name="occurrence",
        ),
    ]
