# Generated by Django 4.2.10 on 2024-08-23 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0036_event_calculated_fields_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourceimageupload",
            name="deployment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manually_uploaded_captures",
                to="main.deployment",
            ),
        ),
    ]
