# Generated by Django 4.2.10 on 2024-09-04 23:22

from django.db import migrations, models
import django.db.models.deletion


# Method to convert blank path to null in bulk
def convert_blank_path_to_null(apps, schema_editor):
    Detection = apps.get_model("main", "Detection")
    Detection.objects.filter(path="").update(path=None)


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0036_event_calculated_fields_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detection",
            name="path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(convert_blank_path_to_null, reverse_code=migrations.RunPython.noop),
    ]
