# Generated by Django 4.2.10 on 2024-10-11 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0037_alter_detection_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detection",
            name="path",
            field=models.CharField(
                blank=True,
                help_text="Either a full URL to a cropped detection image or a relative path to a file in the default project storage. @TODO ensure all detection crops are hosted in the project storage, not the default media storage. Migrate external URLs.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sourceimage",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="captures",
                to="main.event",
            ),
        ),
        migrations.AlterField(
            model_name="sourceimageupload",
            name="deployment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manually_uploaded_captures",
                to="main.deployment",
            ),
        ),
    ]
