# Generated by Django 4.2.10 on 2024-11-26 18:52

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0007_algorithmcategorymap_algorithm_category_map"),
        ("main", "0038_alter_detection_path_alter_sourceimage_event_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classification",
            name="raw_output",
        ),
        migrations.RemoveField(
            model_name="classification",
            name="softmax_output",
        ),
        migrations.AddField(
            model_name="classification",
            name="category_map",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="ml.algorithmcategorymap"
            ),
        ),
        migrations.AddField(
            model_name="classification",
            name="logits",
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name="classification",
            name="scores",
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name="classification",
            name="terminal",
            field=models.BooleanField(
                default=True, help_text="Is this the final classification from a series of classifiers in a pipeline?"
            ),
        ),
        migrations.AddField(
            model_name="taxon",
            name="search_names",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), blank=True, null=True, size=None
            ),
        ),
    ]
