# Generated by Django 4.2.10 on 2025-01-23 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    replaces = [
        ("main", "0039_project_users"),
        ("main", "0007_project_owner"),
        ("main", "0040_merge_0007_project_owner_0039_project_users"),
        ("main", "0041_alter_project_users"),
        ("main", "0042_alter_project_users"),
        ("main", "0043_rename_users_project_members"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0038_alter_detection_path_alter_sourceimage_event_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="members",
            field=models.ManyToManyField(blank=True, related_name="user_projects", to=settings.AUTH_USER_MODEL),
        ),
    ]
