# Generated by Django 4.2.10 on 2025-01-15 22:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0038_alter_detection_path_alter_sourceimage_event_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="users",
            field=models.ManyToManyField(related_name="projects", to=settings.AUTH_USER_MODEL),
        ),
    ]
