# Generated by Django 4.2.10 on 2024-12-05 01:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0039_remove_classification_raw_output_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classification",
            name="logits",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(),
                help_text="The raw output of the last fully connected layer of the model",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="classification",
            name="scores",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(),
                help_text="The probabilities the model, calibrated by the model maker, likely the softmax output",
                null=True,
                size=None,
            ),
        ),
    ]
