# Generated by Django 4.2.10 on 2025-01-17 11:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_project_owner"),
        ("main", "0039_project_users"),
    ]

    operations = []
