# Generated by Django 4.2.10 on 2025-01-19 21:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0040_merge_0007_project_owner_0039_project_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="users",
            field=models.ManyToManyField(related_name="user_projects", to=settings.AUTH_USER_MODEL),
        ),
    ]
