# Generated by Django 4.2.10 on 2025-01-22 14:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0042_alter_project_users"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="users",
            new_name="members",
        ),
    ]
