# Generated by Django 4.2.10 on 2025-01-27 00:10

from django.db import migrations


class Migration(migrations.Migration):
    replaces = [
        ("main", "0044_alter_project_options"),
        ("main", "0045_alter_project_options"),
        ("main", "0046_alter_project_options"),
        ("main", "0047_alter_project_options"),
    ]

    dependencies = [
        ("main", "0039_project_users_squashed_0043_rename_users_project_members"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-priority", "created_at"]},
        ),
    ]
