# Generated by Django 4.2.10 on 2025-01-24 23:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0039_project_users_squashed_0043_rename_users_project_members"),
        ("main", "0040_alter_classification_logits_and_more"),
    ]

    operations = []
