# Generated by Django 4.2.10 on 2025-01-31 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0044_merge_20250124_2333"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxon",
            name="common_name_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="taxon",
            name="rank",
            field=models.CharField(
                choices=[
                    ("KINGDOM", "KINGDOM"),
                    ("PHYLUM", "PHYLUM"),
                    ("CLASS", "CLASS"),
                    ("ORDER", "ORDER"),
                    ("SUPERFAMILY", "SUPERFAMILY"),
                    ("FAMILY", "FAMILY"),
                    ("SUBFAMILY", "SUBFAMILY"),
                    ("TRIBE", "TRIBE"),
                    ("SUBTRIBE", "SUBTRIBE"),
                    ("GENUS", "GENUS"),
                    ("SPECIES", "SPECIES"),
                    ("UNKNOWN", "UNKNOWN"),
                ],
                default="SPECIES",
                max_length=255,
            ),
        ),
    ]
