# Generated by Django 4.2.10 on 2025-02-06 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0017_alter_algorithm_unique_together"),
        ("main", "0044_merge_20250124_2333"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classification",
            name="algorithm",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classifications",
                to="ml.algorithm",
            ),
        ),
    ]
