# Generated by Django 4.2.10 on 2025-02-17 19:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0045_alter_classification_algorithm"),
        ("main", "0045_alter_classification_algorithm_exporthistory"),
    ]

    operations = []
