# Generated by Django 4.2.10 on 2025-02-23 20:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0046_add_taxon_common_name_placeholder"),
        ("main", "0046_merge_20250217_1942"),
    ]

    operations = []
