# Generated by Django 4.2.10 on 2025-02-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0046_add_taxon_common_name_placeholder"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="occurrence",
            index=models.Index(fields=["project", "determination"], name="main_occurr_project_dd7044_idx"),
        ),
    ]
