# Generated by Django 4.2.10 on 2025-02-24 07:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0047_merge_20250223_2003"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExportHistory",
        ),
    ]
