# Generated by Django 4.2.10 on 2025-02-07 10:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0044_merge_20250124_2333"),
        ("main", "0048_alter_project_options_squashed_0051_alter_project_options"),
    ]

    operations = []
