# Generated by Django 4.2.10 on 2025-02-18 14:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0045_alter_classification_algorithm"),
        ("main", "0054_alter_project_options_squashed_0055_alter_project_options"),
    ]

    operations = []
