# Generated by Django 4.2.10 on 2025-02-20 00:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0046_add_taxon_common_name_placeholder"),
        ("main", "0056_merge_20250218_1405"),
    ]

    operations = []
