# Generated by Django 4.2.10 on 2025-03-10 11:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0048_delete_exporthistory"),
        ("main", "0058_alter_project_options"),
    ]

    operations = []
