# Generated by Django 4.2.10 on 2025-05-06 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0059_alter_project_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tags", to="main.project"
                    ),
                ),
                ("taxa", models.ManyToManyField(blank=True, related_name="tags", to="main.taxon")),
            ],
            options={
                "unique_together": {("name", "project")},
            },
        ),
    ]
