# Generated by Django 4.2.10 on 2025-07-09 00:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0059_delete_deprecated_permissions"),
        ("main", "0060_alter_sourceimagecollection_method"),
    ]

    operations = []
