# Generated by Django 4.2.10 on 2025-07-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0060_alter_sourceimagecollection_method"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="event",
            name="unique_event",
        ),
        migrations.RemoveIndex(
            model_name="event",
            name="main_event_group_b_6ce666_idx",
        ),
        migrations.RemoveField(
            model_name="event",
            name="group_by",
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(fields=("deployment", "start", "end"), name="unique_event"),
        ),
    ]
