# Generated by Django 4.2.10 on 2025-04-16 12:27

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):
    replaces = [("main", "0061_classification_features"), ("main", "0062_remove_classification_features_and_more")]

    dependencies = [
        ("main", "0060_add_pgvector_extension"),
    ]

    operations = [
        migrations.AddField(
            model_name="classification",
            name="features_2048",
            field=pgvector.django.vector.VectorField(
                default=None, dimensions=2048, help_text="Feature embedding from the model backbone", null=True
            ),
        ),
    ]
