# Generated by Django 4.2.10 on 2025-05-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0060_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="taxa",
        ),
        migrations.AddField(
            model_name="taxon",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="taxa", to="main.tag"),
        ),
    ]
