# Generated by Django 4.2.10 on 2025-07-28 19:05

import ami.main.models
from django.db import migrations
import django_pydantic_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0061_tag_taxon_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="feature_flags",
            field=django_pydantic_field.fields.PydanticSchemaField(
                blank=True, config=None, default={"tags": False}, schema=ami.main.models.ProjectFeatureFlags
            ),
        ),
    ]
