# Generated by Django 4.2.10 on 2025-04-14 10:14

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0061_classification_features_squashed_0062_remove_classification_features_and_more.py"),
    ]

    operations = [
        migrations.AddField(
            model_name="classification",
            name="features",
            field=pgvector.django.vector.VectorField(
                dimensions=2048, help_text="Feature embedding from the model backbone", null=True
            ),
        ),
    ]
