# Generated by Django 4.2.10 on 2025-04-25 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0061_classification_features_squashed_0062_remove_classification_features_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classification",
            name="ood_score",
            field=models.FloatField(blank=True, help_text="Out of distribution score", null=True),
        ),
        migrations.AddField(
            model_name="occurrence",
            name="determination_ood_score",
            field=models.FloatField(blank=True, help_text="Out of distribution score", null=True),
        ),
        migrations.AlterField(
            model_name="occurrence",
            name="determination",
            field=models.ForeignKey(
                help_text="The Taxon assigned to this occurrence",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="occurrences",
                to="main.taxon",
            ),
        ),
        migrations.AlterField(
            model_name="occurrence",
            name="determination_score",
            field=models.FloatField(blank=True, help_text="Estimation of confidence", null=True),
        ),
    ]
