# Generated by Django 4.2.10 on 2025-04-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0062_classification_ood_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxon",
            name="unknown_species",
            field=models.BooleanField(default=False, help_text="Is this a clustering-generated taxon"),
        ),
    ]
