# Generated by Django 4.2.10 on 2025-07-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0062_project_feature_flags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourceimagecollection",
            name="method",
            field=models.CharField(
                choices=[
                    ("full", "full"),
                    ("random", "random"),
                    ("stratified_random", "stratified_random"),
                    ("interval", "interval"),
                    ("manual", "manual"),
                    ("starred", "starred"),
                    ("random_from_each_event", "random_from_each_event"),
                    ("last_and_random_from_each_event", "last_and_random_from_each_event"),
                    ("greatest_file_size_from_each_event", "greatest_file_size_from_each_event"),
                    ("detections_only", "detections_only"),
                    ("common_combined", "common_combined"),
                ],
                default="full",
                max_length=255,
            ),
        ),
    ]
