# Generated by Django 4.2.10 on 2025-08-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0063_alter_sourceimagecollection_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
