# Generated by Django 4.2.10 on 2025-08-11 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0022_alter_pipeline_default_config"),
        ("main", "0064_alter_project_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="default_filters_exclude_taxa",
            field=models.ManyToManyField(
                blank=True,
                help_text="Taxa that are excluded by default in the occurrence filters and metrics. For example, 'Not a Moth'.",
                related_name="exlude_taxa_default_projects",
                to="main.taxon",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="default_filters_include_taxa",
            field=models.ManyToManyField(
                blank=True,
                help_text="Taxa that are included by default in the occurrence filters and metrics. For example, the top-level taxa like 'Moths' or 'Arthropods'. ",
                related_name="include_taxa_default_projects",
                to="main.taxon",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="default_filters_score_threshold",
            field=models.FloatField(default=0.5, help_text="Default score threshold for filtering occurrences"),
        ),
        migrations.AddField(
            model_name="project",
            name="default_processing_pipeline",
            field=models.ForeignKey(
                blank=True,
                help_text="The default pipeline to use for processing images in this project. This is used to determine which processing service to run on new images. ",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_projects",
                to="ml.pipeline",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="session_time_gap_seconds",
            field=models.IntegerField(default=7200, help_text="Time gap in seconds to consider a new session"),
        ),
    ]
