# Generated by Django 4.2.10 on 2025-05-01 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0064_taxon_cover_image_credit_taxon_cover_image_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrence",
            name="determination_classification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="occurrences",
                to="main.classification",
            ),
        ),
        migrations.AddField(
            model_name="occurrence",
            name="determination_identification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="occurrences",
                to="main.identification",
            ),
        ),
    ]
