# Generated by Django 4.2.10 on 2025-05-07 15:26

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.vector


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0023_alter_algorithm_task_type"),
        ("main", "0064_taxon_cover_image_credit_taxon_cover_image_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="detection",
            name="favorite",
            field=models.BooleanField(default=False, help_text="Use this detection to represent the occurrence"),
        ),
        migrations.AddField(
            model_name="occurrence",
            name="best_detection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="occurrence_representing",
                to="main.detection",
            ),
        ),
        migrations.AddField(
            model_name="occurrence",
            name="best_identification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="occurrences",
                to="main.identification",
            ),
        ),
        migrations.AddField(
            model_name="occurrence",
            name="best_prediction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="occurrences",
                to="main.classification",
            ),
        ),
        migrations.AddField(
            model_name="occurrence",
            name="favorite",
            field=models.BooleanField(default=False, help_text="Is this a good representative occurrence?"),
        ),
        migrations.AddField(
            model_name="occurrence",
            name="mean_feature_vector",
            field=pgvector.django.vector.VectorField(
                default=None,
                dimensions=2048,
                help_text="Mean feature vector of all detections in this occurrence",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="occurrence",
            name="mean_feature_vector_algorithm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="occurrences",
                to="ml.algorithm",
            ),
        ),
    ]
