# Generated by Django 4.2.10 on 2025-05-10 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0064_taxon_cover_image_credit_taxon_cover_image_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxonObserved",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "example_occurrence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="taxon_observed",
                        to="main.occurrence",
                    ),
                ),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="main.project")),
                ("taxon", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="main.taxon")),
            ],
            options={
                "unique_together": {("taxon", "project")},
            },
        ),
        migrations.AddField(
            model_name="taxon",
            name="observed_projects",
            field=models.ManyToManyField(related_name="oberved_taxa", through="main.TaxonObserved", to="main.project"),
        ),
    ]
