# Generated by Django 4.2.10 on 2025-05-09 19:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0061_remove_tag_taxa_taxon_tags"),
        ("main", "0064_taxon_cover_image_credit_taxon_cover_image_url_and_more"),
    ]

    operations = []
