# Generated by Django 4.2.10 on 2025-05-11 15:09

from django.db import migrations
from django.core.management import call_command


def populate_cached_occurrence_fields(apps, schema_editor):
    """
    Populate cached fields for all occurrences using our management command.

    We run this as a separate command because it's complex and needs full access
    to model methods which aren't available in migrations.
    """
    # Call the management command we've created
    print("Calling management command to update occurrence determination fields...")
    call_command("update_occurrence_determinations")
    print("Management command completed.")


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0065_detection_favorite_occurrence_best_detection_and_more"),
    ]

    operations = [
        migrations.RunPython(
            populate_cached_occurrence_fields,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
