# Generated by Django 4.2.10 on 2025-05-12 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0065_merge_20250509_1905"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="main.project",
            ),
        ),
    ]
