# Generated by Django 4.2.10 on 2025-08-08 21:53

import ami.main.models
from django.db import migrations, models
import django_pydantic_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0065_project_default_filters_exclude_taxa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="feature_flags",
            field=django_pydantic_field.fields.PydanticSchemaField(
                blank=True,
                config=None,
                default={"auto_processs_manual_uploads": False, "tags": False},
                schema=ami.main.models.ProjectFeatureFlags,
            ),
        ),
        migrations.AlterField(
            model_name="sourceimageupload",
            name="image",
            field=models.ImageField(upload_to=ami.main.models.upload_to_with_deployment),
        ),
    ]
