# Generated by Django 4.2.10 on 2025-05-12 11:38

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.vector


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0023_alter_algorithm_task_type"),
        ("main", "0065_taxonobserved_taxon_observed_projects"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectTaxon",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mean_feature_vector",
                    pgvector.django.vector.VectorField(
                        default=None,
                        dimensions=2048,
                        help_text="Cluster center for this taxon in this project",
                        null=True,
                    ),
                ),
                (
                    "example_occurrence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="taxon_observed",
                        to="main.occurrence",
                    ),
                ),
                (
                    "mean_feature_vector_algorithm",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="taxa_observed",
                        to="ml.algorithm",
                    ),
                ),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="main.project")),
                ("taxon", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="main.taxon")),
            ],
            options={
                "unique_together": {("taxon", "project")},
            },
        ),
        migrations.DeleteModel(
            name="TaxonObserved",
        ),
        migrations.AlterField(
            model_name="taxon",
            name="observed_projects",
            field=models.ManyToManyField(related_name="project_taxa", through="main.ProjectTaxon", to="main.project"),
        ),
    ]
