# Generated by Django 4.2.10 on 2025-05-16 16:14

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.vector


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0023_alter_algorithm_task_type"),
        ("main", "0066_tag_taxon_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="detection",
            old_name="favorite",
            new_name="featured",
        ),
        migrations.AddField(
            model_name="detection",
            name="featured_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="occurrence",
            name="featured",
            field=models.BooleanField(default=False, help_text="Use this occurrence to represent a Taxon in the UI"),
        ),
        migrations.AddField(
            model_name="occurrence",
            name="featured_at",
            field=models.DateTimeField(
                blank=True, help_text="The date and time this occurrence was featured", null=True
            ),
        ),
        migrations.AlterField(
            model_name="taxon",
            name="projects",
            field=models.ManyToManyField(blank=True, related_name="taxa", to="main.project"),
        ),
        migrations.CreateModel(
            name="ProjectTaxon",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mean_feature_vector",
                    pgvector.django.vector.VectorField(
                        default=None,
                        dimensions=2048,
                        help_text="Cluster center for this taxon in this project",
                        null=True,
                    ),
                ),
                (
                    "featured_detection",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="main.detection"
                    ),
                ),
                (
                    "featured_occcurence",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="main.occurrence"
                    ),
                ),
                (
                    "mean_feature_vector_algorithm",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="ml.algorithm"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="project_taxa", to="main.project"
                    ),
                ),
                (
                    "taxon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="project_taxa", to="main.taxon"
                    ),
                ),
            ],
            options={
                "unique_together": {("taxon", "project")},
            },
        ),
    ]
