# Generated by Django 4.2.10 on 2025-05-12 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0066_projecttaxon_delete_taxonobserved_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projecttaxon",
            name="example_occurrence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_taxa",
                to="main.occurrence",
            ),
        ),
    ]
