# Generated by Django 4.2.10 on 2025-08-15 21:01

import ami.main.models
from django.db import migrations
import django_pydantic_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0066_alter_project_feature_flags_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="feature_flags",
            field=django_pydantic_field.fields.PydanticSchemaField(
                blank=True,
                config=None,
                default={"auto_process_manual_uploads": False, "reprocess_existing_detections": False, "tags": False},
                schema=ami.main.models.ProjectFeatureFlags,
            ),
        ),
    ]
