# Generated by Django 4.2.10 on 2025-05-15 21:23

from django.db import migrations, models
import django.db.models.deletion


def add_inital_tags(apps, schema_editor):
    """
    Add initial tags to the database.
    """
    Tag = apps.get_model("main", "Tag")

    # Make tags available for all projects
    project = None

    # Create initial tags
    tags = [
        "most wanted",
        "also wanted",
        "reviewed",
        "collected",
    ]

    for tag in tags:
        Tag.objects.get_or_create(name=tag, project=project)


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0066_populate_cached_occurence_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="main.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "project")},
            },
        ),
        migrations.AddField(
            model_name="taxon",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="taxa", to="main.tag"),
        ),
        migrations.RunPython(add_inital_tags, migrations.RunPython.noop),
    ]
