# Generated by Django 4.2.10 on 2025-05-29 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0066_alter_taxalist_projects_alter_taxon_projects_tag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="detection",
            name="next_detection",
            field=models.OneToOneField(
                blank=True,
                help_text="The detection that follows this one in the tracking sequence.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous_detection",
                to="main.detection",
            ),
        ),
    ]
