# Generated by Django 4.2.10 on 2025-05-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0067_tag_taxon_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxon",
            name="projects",
            field=models.ManyToManyField(blank=True, related_name="taxa", to="main.project"),
        ),
    ]
