# Generated by Django 4.2.10 on 2025-06-09 11:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0060_taxon_cover_image_credit_taxon_cover_image_url_and_more"),
        ("main", "0066_alter_taxalist_projects_alter_taxon_projects_tag_and_more"),
        ("main", "0066_populate_cached_occurence_fields"),
        ("main", "0068_allow_taxa_without_project"),
    ]

    operations = []
