# Generated by Django 4.2.10 on 2025-08-18 12:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0067_alter_project_feature_flags"),
        ("main", "0068_alter_project_options"),
    ]

    operations = []
