# Generated by Django 4.2.10 on 2025-08-29 04:29

import ami.main.models
from django.db import migrations
import django_pydantic_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0069_merge_20250818_1201"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="feature_flags",
            field=django_pydantic_field.fields.PydanticSchemaField(
                blank=True,
                config=None,
                default={
                    "auto_process_manual_uploads": False,
                    "default_filters": False,
                    "reprocess_existing_detections": False,
                    "tags": False,
                },
                schema=ami.main.models.ProjectFeatureFlags,
            ),
        ),
    ]
