# Generated by Django 4.2.10 on 2025-08-22 16:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0062_project_draft"),
        ("main", "0069_merge_20250818_1201"),
    ]

    operations = []
