# Generated by Django 4.2.10 on 2025-04-14 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0069_merge_20250818_1201"),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql="DROP EXTENSION IF EXISTS vector;",
        ),
    ]
