# Generated by Django 4.2.10 on 2025-08-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0069_merge_20250818_1201"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="draft",
            field=models.BooleanField(default=False, help_text="Indicates whether this project is in draft mode"),
        ),
    ]
