# Generated by Django 4.2.10 on 2025-08-29 10:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0070_alter_project_feature_flags"),
        ("main", "0070_alter_project_options"),
    ]

    operations = []
