# Generated by Django 4.2.10 on 2025-09-12 01:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0071_alter_project_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="draft",
            field=models.BooleanField(default=False, help_text="Indicates whether this project is in draft mode"),
        ),
    ]
