# Generated by Django 4.2.10 on 2025-09-16 21:20

import ami.main.models
from django.db import migrations
import django_pydantic_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0072_project_draft"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="feature_flags",
            field=django_pydantic_field.fields.PydanticSchemaField(
                blank=True,
                config=None,
                default=ami.main.models.get_default_feature_flags,
                schema=ami.main.models.ProjectFeatureFlags,
            ),
        ),
    ]
