# Generated by Django 4.2.10 on 2025-09-17 00:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0073_alter_project_feature_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxon",
            name="cover_image_credit",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="taxon",
            name="cover_image_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="taxon",
            name="fieldguide_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
