# Generated by Django 4.2.10 on 2025-09-22 01:30

from django.db import migrations


def refresh_deployment_counts(apps, schema_editor):
    Deployment = apps.get_model("main", "Deployment")
    for dep in Deployment.objects.all():
        dep.save()  # triggers save logic and recalculates counts


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0074_taxon_cover_image_credit_taxon_cover_image_url_and_more"),
    ]

    operations = [
        migrations.RunPython(refresh_deployment_counts, reverse_code=migrations.RunPython.noop),
    ]
