# Generated by Django 4.2.10 on 2025-09-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0074_taxon_cover_image_credit_taxon_cover_image_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="s3storagesource",
            name="region",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
