# Generated by Django 4.2.10 on 2025-10-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0075_auto_20250922_0130"),
    ]

    # Allow this migration to run outside a transaction to support CONCURRENTLY
    atomic = False

    operations = [
        migrations.AddIndex(
            model_name="occurrence",
            index=models.Index(
                fields=["determination_id", "project_id", "event_id", "determination_score"],
                name="occur_det_proj_evt_score",
            ),
        ),
        migrations.AddIndex(
            model_name="occurrence",
            index=models.Index(fields=["determination_id", "project_id", "event_id"], name="occur_det_proj_evt"),
        ),
    ]
