# Generated by Django 4.2.10 on 2025-10-14 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0075_alter_project_options"),
        ("main", "0076_add_occurrence_composite_indexes"),
    ]

    operations = []
