# Generated by Django 4.2.10 on 2025-10-14 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0077_merge_20251014_1426"),
    ]

    operations = [
        migrations.AddField(
            model_name="classification",
            name="applied_to",
            field=models.ForeignKey(
                blank=True,
                help_text="If this classification was produced by a post-processing algorithm, this field references the original classification it was applied to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_classifications",
                to="main.classification",
            ),
        ),
    ]
