# Generated by Django 4.2.10 on 2025-12-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0078_classification_applied_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="s3storagesource",
            name="region",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
