# Generated by Django 4.2.10 on 2025-10-29 11:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0080_alter_project_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-priority", "created_at"],
                "permissions": [
                    ("create_identification", "Can create identifications"),
                    ("update_identification", "Can update identifications"),
                    ("delete_identification", "Can delete identifications"),
                    ("create_job", "Can create a job"),
                    ("update_job", "Can update a job"),
                    ("run_ml_job", "Can run/retry/cancel ML jobs"),
                    ("run_populate_captures_collection_job", "Can run/retry/cancel Populate Collection jobs"),
                    ("run_data_storage_sync_job", "Can run/retry/cancel Data Storage Sync jobs"),
                    ("run_data_export_job", "Can run/retry/cancel Data Export jobs"),
                    ("run_single_image_ml_job", "Can process a single capture"),
                    ("run_post_processing_job", "Can run/retry/cancel Post-Processing jobs"),
                    ("delete_job", "Can delete a job"),
                    ("create_deployment", "Can create a deployment"),
                    ("delete_deployment", "Can delete a deployment"),
                    ("update_deployment", "Can update a deployment"),
                    ("sync_deployment", "Can sync images to a deployment"),
                    ("create_sourceimagecollection", "Can create a collection"),
                    ("update_sourceimagecollection", "Can update a collection"),
                    ("delete_sourceimagecollection", "Can delete a collection"),
                    ("populate_sourceimagecollection", "Can populate a collection"),
                    ("create_sourceimage", "Can create a source image"),
                    ("update_sourceimage", "Can update a source image"),
                    ("delete_sourceimage", "Can delete a source image"),
                    ("star_sourceimage", "Can star a source image"),
                    ("create_sourceimageupload", "Can create a source image upload"),
                    ("update_sourceimageupload", "Can update a source image upload"),
                    ("delete_sourceimageupload", "Can delete a source image upload"),
                    ("create_s3storagesource", "Can create storage"),
                    ("delete_s3storagesource", "Can delete storage"),
                    ("update_s3storagesource", "Can update storage"),
                    ("test_s3storagesource", "Can test storage connection"),
                    ("create_site", "Can create a site"),
                    ("delete_site", "Can delete a site"),
                    ("update_site", "Can update a site"),
                    ("create_device", "Can create a device"),
                    ("delete_device", "Can delete a device"),
                    ("update_device", "Can update a device"),
                    ("view_private_data", "Can view private data"),
                    ("trigger_exports", "Can trigger data exports"),
                    ("create_project", "Can create a project"),
                    ("create_processingservice", "Can create processing service"),
                    ("delete_processingservice", "Can delete processing service"),
                    ("update_processingservice", "Can update processing service"),
                    ("register_pipelines_processingservice", "Can register pipelines for processing service"),
                    ("create_taxon", "Can create taxon"),
                    ("update_taxon", "Can update taxon"),
                    ("delete_taxon", "Can delete taxon"),
                    ("assign_tags_taxon", "Can assign tags to taxon"),
                ],
            },
        ),
    ]
