# Generated by Django 4.2.10 on 2026-01-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0080_userprojectmembership"),
    ]

    operations = [
        migrations.AddField(
            model_name="s3storagesource",
            name="region",
            field=models.CharField(
                blank=True,
                help_text="AWS region (e.g., 'us-east-1', 'eu-west-1'). Leave blank for Swift/MinIO storage.",
                max_length=255,
                null=True,
            ),
        ),
    ]
