# Generated by Django 4.2.10 on 2026-01-31 04:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0081_alter_project_options"),
        ("main", "0081_s3storagesource_region"),
    ]

    operations = []
