# Generated by Django 4.2.10

import ami.main.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0082_add_taxalist_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="deployment",
            name="time_zone",
            field=models.CharField(
                default="America/New_York",
                help_text="IANA time zone identifier (e.g. 'America/New_York', 'Europe/London').",
                max_length=63,
                validators=[ami.main.models.validate_time_zone],
            ),
        ),
    ]
