# Generated by Django 4.2.10 on 2026-05-13 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0084_revoke_delete_job_from_roles"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceImageThumbnail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("path", models.CharField(blank=True, max_length=255)),
                ("label", models.CharField(blank=True, max_length=255, null=True)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("size", models.BigIntegerField(blank=True, null=True)),
                ("last_modified", models.DateTimeField(blank=True, null=True)),
                (
                    "source_image",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="thumbnails",
                        to="main.sourceimage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
