# Generated by Django 4.2.10 on 2026-05-26 14:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0085_sourceimagethumbnail"),
        ("main", "0086_sourceimage_recent_capture_index"),
    ]

    operations = []
