# Generated by Django 4.2.10 on 2026-05-13 20:05

import ami.base.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0086_backfill_sourceimagecollection_counts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deployment",
            name="captures_count",
            field=ami.base.models.CachedCountField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deployment",
            name="detections_count",
            field=ami.base.models.CachedCountField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deployment",
            name="events_count",
            field=ami.base.models.CachedCountField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deployment",
            name="occurrences_count",
            field=ami.base.models.CachedCountField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deployment",
            name="taxa_count",
            field=ami.base.models.CachedCountField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="captures_count",
            field=ami.base.models.CachedCountField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="detections_count",
            field=ami.base.models.CachedCountField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="occurrences_count",
            field=ami.base.models.CachedCountField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sourceimage",
            name="detections_count",
            field=ami.base.models.CachedCountField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sourceimagecollection",
            name="source_images_count",
            field=ami.base.models.CachedCountField(default=0),
        ),
        migrations.AlterField(
            model_name="sourceimagecollection",
            name="source_images_processed_count",
            field=ami.base.models.CachedCountField(default=0),
        ),
        migrations.AlterField(
            model_name="sourceimagecollection",
            name="source_images_with_detections_count",
            field=ami.base.models.CachedCountField(default=0),
        ),
    ]
