# Generated by Django 4.2.10 on 2026-05-28 14:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0087_merge_20260526_1423"),
        ("main", "0087_taxon_parents_json_gin_index"),
    ]

    operations = []
