# Generated by Django 4.2.10 on 2026-05-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0087_taxon_parents_json_gin_index"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="detection",
            index=models.Index(fields=["source_image", "-created_at"], name="det_srcimg_created_idx"),
        ),
    ]
