# Generated by Django 4.2.10 on 2026-06-03 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0088_detection_det_srcimg_created_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceImageThumbnail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("path", models.CharField(blank=True, max_length=255)),
                ("label", models.CharField(max_length=255)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("size", models.BigIntegerField(blank=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "source_image",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="thumbnails",
                        to="main.sourceimage",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["source_image", "label"], name="main_source_source__b0d4cd_idx")],
            },
        ),
        migrations.AddConstraint(
            model_name="sourceimagethumbnail",
            constraint=models.UniqueConstraint(
                fields=("source_image", "label"), name="unique_source_image_thumbnail_label"
            ),
        ),
    ]
