# Generated by Django 4.2.10 on 2026-06-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0089_add_regroup_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="session_time_gap_seconds",
            field=models.IntegerField(
                default=7200,
                help_text='Maximum gap between consecutive captures (in seconds) before a new session is started. Changing this value does not regroup existing captures automatically — to apply, select the affected deployments on the Deployments admin page and run the "Regroup captures into sessions" action.',
            ),
        ),
    ]
