# Generated by Django 4.2.10 on 2026-06-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0090_sourceimagethumbnail_cascade_source_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourceimage",
            name="checksum",
            field=models.CharField(
                blank=True,
                help_text="Checksum of the image file, read from the source file in image storage.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sourceimage",
            name="checksum_algorithm",
            field=models.CharField(
                blank=True, help_text="Algorithm used for the checksum (e.g. MD5, SHA256).", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sourceimage",
            name="last_modified",
            field=models.DateTimeField(
                blank=True,
                help_text="When the image file was last modified, read from the source file in image storage.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sourceimage",
            name="size",
            field=models.BigIntegerField(
                blank=True,
                help_text="Size of the image file in bytes, read from the source file in image storage.",
                null=True,
            ),
        ),
    ]
