# Generated by Django 4.2.10 on 2026-07-02 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0028_normalize_empty_endpoint_url_to_null"),
        ("main", "0094_enable_async_pipeline_workers"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="default_taxa_list",
            field=models.ForeignKey(
                blank=True,
                help_text="Fall-back taxa list for occurrences whose research site has none of its own.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="main.taxalist",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="region_code",
            field=models.CharField(
                blank=True,
                help_text="A region identifier for region_source (a GADM gid or an iNaturalist place id).",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="region_source",
            field=models.CharField(
                blank=True,
                choices=[("gbif_gadm", "GBIF (GADM region)"), ("inat_place", "iNaturalist (place)")],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="region_code",
            field=models.CharField(
                blank=True,
                help_text="A region identifier for region_source (a GADM gid or an iNaturalist place id).",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="region_source",
            field=models.CharField(
                blank=True,
                choices=[("gbif_gadm", "GBIF (GADM region)"), ("inat_place", "iNaturalist (place)")],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="taxa_list",
            field=models.ForeignKey(
                blank=True,
                help_text="Taxa list to use for occurrences at this research site (e.g. for class masking).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="main.taxalist",
            ),
        ),
        migrations.AddField(
            model_name="taxon",
            name="covered_by_algorithms",
            field=models.ManyToManyField(
                blank=True,
                help_text="Algorithm(s) whose category map includes this taxon as a label.",
                related_name="covered_taxa",
                to="ml.algorithm",
            ),
        ),
        migrations.AddField(
            model_name="taxon",
            name="has_model_coverage",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True iff covered_by_algorithms is non-empty. Denormalized for cheap filtering.",
            ),
        ),
    ]
