# Generated by Django 4.2.10 on 2026-09-13 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0095_grant_sync_deployment_to_mldatamanager"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="default_taxa_list",
            field=models.ForeignKey(
                blank=True,
                help_text="The species this project expects to see. Used as the class list when retraining a classifier head, so the head covers the region rather than only the species someone happened to verify.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for_projects",
                to="main.taxalist",
            ),
        ),
    ]
