# Generated by Django 4.2.10 on 2026-09-04 18:34

import ami.main.models
from django.db import migrations, models
import django.db.models.deletion
import django_pydantic_field.fields
import typing


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0095_grant_sync_deployment_to_mldatamanager"),
    ]

    operations = [
        migrations.AddField(
            model_name="deployment",
            name="last_status",
            field=django_pydantic_field.fields.PydanticSchemaField(
                blank=True, config=None, default=None, null=True, schema=ami.main.models.StationStatusPayload | None
            ),
        ),
        migrations.AddField(
            model_name="deployment",
            name="last_status_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="DeploymentStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recorded_at",
                    models.DateTimeField(help_text="When the station recorded this status, by its own clock."),
                ),
                (
                    "status",
                    django_pydantic_field.fields.PydanticSchemaField(
                        blank=True,
                        config=None,
                        default=ami.main.models.get_default_station_status,
                        schema=ami.main.models.StationStatusPayload,
                    ),
                ),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_reports",
                        to="main.deployment",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Deployment statuses",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(fields=["deployment", "-recorded_at"], name="main_deploy_deploym_ccc35f_idx")
                ],
            },
        ),
    ]
