# Generated by Django 4.2.10 on 2026-10-05 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0023_alter_job_job_type_key"),
        ("main", "0095_grant_sync_deployment_to_mldatamanager"),
    ]

    operations = [
        migrations.AddField(
            model_name="classification",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classifications",
                to="jobs.job",
            ),
        ),
        migrations.AddField(
            model_name="detection",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="detections",
                to="jobs.job",
            ),
        ),
    ]
