# Generated by Django 4.2.10 on 2026-09-07 19:31

import ami.main.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0095_grant_sync_deployment_to_mldatamanager"),
    ]

    operations = [
        migrations.AddField(
            model_name="deployment",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Free-form JSON object holding attributes specific to this configuration, beyond the fields modelled natively. Camera height or habitat description, for example.",
                validators=[ami.main.models.validate_metadata_object],
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Free-form JSON object holding attributes specific to this configuration, beyond the fields modelled natively. Camera height or habitat description, for example.",
                validators=[ami.main.models.validate_metadata_object],
            ),
        ),
    ]
