# Generated by Django 4.2.10 on 2026-10-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0096_detection_next_detection"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrence",
            name="track_distinct_taxa",
            field=models.IntegerField(
                blank=True,
                help_text="Distinct taxa among terminal classifications. See models_future/track_stats.py.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="occurrence",
            name="track_id_agreement",
            field=models.FloatField(
                blank=True,
                help_text="Share of terminal classifications naming the determination. See models_future/track_stats.py.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="occurrence",
            name="track_motion",
            field=models.FloatField(
                blank=True,
                help_text="Path length between captures as a fraction of the image diagonal. See track_stats.py.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="occurrence",
            name="track_size_ratio",
            field=models.FloatField(
                blank=True,
                help_text="Largest box area over the smallest. See models_future/track_stats.py.",
                null=True,
            ),
        ),
    ]
