# Generated by Django 4.2.10 on 2026-10-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0097_detection_and_classification_job_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="deployment",
            name="frame_long_side_mm",
            field=models.FloatField(
                blank=True,
                help_text="Length of the longer edge of the camera's view, measured on the sheet, in millimetres.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="deployment",
            name="frame_short_side_mm",
            field=models.FloatField(
                blank=True,
                help_text="Length of the shorter edge of the camera's view, measured on the sheet, in millimetres. Captures whose aspect ratio does not match are treated as uncalibrated.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="occurrence",
            name="length_mm",
            field=models.FloatField(
                blank=True,
                help_text="Median length of the longest side of this occurrence's detection boxes in millimetres. Approximate: the box can include legs, antennae and blur. Empty when the station's field of view is not calibrated.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="occurrence",
            name="relative_length",
            field=models.FloatField(
                blank=True,
                help_text="Median length of the longest side of this occurrence's detection boxes, as a fraction of the longest side of the capture. Empty when no detection has a usable box.",
                null=True,
            ),
        ),
    ]
