# Generated by Django 4.2.10 on 2026-09-02 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0098_detection_next_detection"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrence",
            name="grouping_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="occurrence",
            name="grouping_verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_occurrence_groupings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
