# Generated by Django 4.2.10 on 2026-09-09 12:00
#
# Stored track statistics so the occurrence list can sort by them. No indexes: the list
# is always filtered by project first, and the sort runs over that project's rows.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0099_occurrence_grouping_verification"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrence",
            name="track_motion",
            field=models.FloatField(
                blank=True,
                help_text="Path length between frames as a fraction of the frame diagonal. See models_future/track_stats.py.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="occurrence",
            name="track_size_ratio",
            field=models.FloatField(
                blank=True,
                help_text="Largest box area over the smallest. See models_future/track_stats.py.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="occurrence",
            name="track_distinct_taxa",
            field=models.IntegerField(
                blank=True,
                help_text="Distinct taxa among terminal classifications. See models_future/track_stats.py.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="occurrence",
            name="track_id_agreement",
            field=models.FloatField(
                blank=True,
                help_text="Share of terminal classifications naming the determination. See models_future/track_stats.py.",
                null=True,
            ),
        ),
    ]
