# Generated by Django 4.2.10 on 2026-09-15 02:01
#
# Additive: creates an empty table. The unique constraint's index, which leads with
# detection_id, also serves reads of the vectors for a set of detections. See #1417.

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.vector


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0028_normalize_empty_endpoint_url_to_null"),
        ("main", "0101_grant_run_post_processing_to_ml_data_manager"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectionEmbedding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "features_2048",
                    pgvector.django.vector.VectorField(
                        dimensions=2048, help_text="Feature embedding from the model backbone"
                    ),
                ),
                (
                    "algorithm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detection_embeddings",
                        to="ml.algorithm",
                    ),
                ),
                (
                    "detection",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="main.detection",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="detectionembedding",
            constraint=models.UniqueConstraint(
                fields=("detection", "algorithm"), name="unique_detection_embedding_per_algorithm"
            ),
        ),
    ]
