# Generated by Django 4.2.10 on 2026-10-01 22:19
#
# Additive: an empty table, and a nullable job column on detections and classifications that
# existing rows leave null. The vector column is stored uncompressed out of line (STORAGE
# EXTERNAL): vectors do not compress, and it keeps the table's rows small. See #1453.

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pgvector.django.halfvec


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0029_algorithm_embedding_dimensions"),
        ("jobs", "0023_alter_job_job_type_key"),
        ("main", "0101_grant_run_post_processing_to_ml_data_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="classification",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classifications",
                to="jobs.job",
            ),
        ),
        migrations.AddField(
            model_name="detection",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="detections",
                to="jobs.job",
            ),
        ),
        migrations.CreateModel(
            name="DetectionEmbedding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("key", models.CharField(default="embedding", max_length=255)),
                (
                    "vector",
                    pgvector.django.halfvec.HalfVectorField(help_text="The feature vector, in half precision."),
                ),
                (
                    "algorithm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)ss", to="ml.algorithm"
                    ),
                ),
                (
                    "detection",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="main.detection",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)ss",
                        to="jobs.job",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)ss", to="main.project"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="detectionembedding",
            constraint=models.CheckConstraint(
                check=models.Q(("key", ""), _negated=True), name="main_detectionembedding_key_not_empty"
            ),
        ),
        migrations.AddConstraint(
            model_name="detectionembedding",
            constraint=models.UniqueConstraint(
                fields=("detection", "algorithm", "key"), name="main_detectionembedding_unique_detection_algorithm_key"
            ),
        ),
        migrations.RunSQL(
            sql="ALTER TABLE main_detectionembedding ALTER COLUMN vector SET STORAGE EXTERNAL",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
