# Generated by Django 4.2.10 on 2026-10-08 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0101_grant_train_classifier_job_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="default_taxa_list",
            field=models.ForeignKey(
                blank=True,
                help_text="The species this project expects to see. Used as the class list when retraining a classifier head, so the head covers the region rather than only the species someone happened to verify.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for_projects",
                to="main.taxalist",
            ),
        ),
    ]
