# Generated by Django 4.2.10 on 2026-09-23 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0028_normalize_empty_endpoint_url_to_null"),
        ("jobs", "0023_alter_job_job_type_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0102_detection_embedding"),
    ]

    operations = [
        migrations.CreateModel(
            name="OccurrenceHistoryRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("algorithm_result", "Algorithm Result"), ("review", "Review")], max_length=32
                    ),
                ),
                ("subtype", models.CharField(max_length=64)),
                ("timestamp", models.DateTimeField()),
                ("payload", models.JSONField(default=dict)),
                (
                    "algorithm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ml.algorithm",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="jobs.job",
                    ),
                ),
                (
                    "occurrence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="history", to="main.occurrence"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["occurrence", "-timestamp"], name="occur_history_occ_time_idx")],
            },
        ),
    ]
