import logging

import rest_framework.request
from django.http import Http404
from rest_framework import serializers

from ami.main.models import Project

logger = logging.getLogger(__name__)


def get_active_project(
    request: rest_framework.request.Request,
    kwargs: dict | None = None,
    required: bool = False,
) -> Project | None:
    """
    Extract and return the active project from a request.

    Args:
        request: The DRF request object
        kwargs: URL kwargs (optional, used to extract pk from URL paths)
        require_project: Whether project_id is required (raises validation error if True and not found)

    Returns:
        Project instance if found, None otherwise (let the caller handle None case)
    """
    from ami.base.serializers import SingleParamSerializer

    param = "project_id"

    project_id = None
    # Support nested routers: /projects/{project_pk}/members/{pk}
    if kwargs and "project_pk" in kwargs:
        project_id = kwargs["project_pk"]
    # Extract from URL if `/projects/` is in the url path
    elif kwargs and "/projects/" in request.path:
        project_id = kwargs.get("pk")

    # If not in URL, try query parameters
    if not project_id:
        # Look for project_id in GET query parameters or POST data
        # request.data may not always be a dict (e.g., for non-POST requests), so we check its type
        post_data = request.data if isinstance(request.data, dict) else {}
        project_id = request.query_params.get(param) or post_data.get(param)

        project_id = SingleParamSerializer[int].clean(
            param_name=param,
            field=serializers.IntegerField(required=required, min_value=0),
            data={param: project_id} if project_id else {},
        )

    if not project_id:
        return None

    try:
        return Project.objects.get(id=project_id)
    except Project.DoesNotExist:
        return None


class ProjectMixin:
    """
    Mixin to help views extract the active project from the request.
    """

    require_project = False  # Project required for all actions
    require_project_for_list = True  # Project required for list actions
    request: rest_framework.request.Request
    kwargs: dict  # This is is generated by DRF from the URL pattern /api/projects/{project_id:int}/

    def get_active_project(self) -> Project | None:
        """
        Instance method wrapper around the standalone get_active_project function.

        Enforcement logic:
        - If require_project is True, project_id is required for all actions.
        - If require_project_for_list is True (default), project_id is required for list actions.
        - Missing project_id when required raises ValidationError (400).
        - Valid project_id pointing to nonexistent project raises Http404 (404).
        """
        action = getattr(self, "action", None)
        required = self.require_project or (self.require_project_for_list and action == "list")

        project = get_active_project(
            request=self.request,
            kwargs=self.kwargs,
            required=required,
        )

        if not project and required:
            # Missing project_id is already caught by ValidationError in get_active_project().
            # This handles: valid project_id was provided but the project doesn't exist.
            raise Http404("Project not found.")

        return project
