export enum STRING {
  /* NAV_ITEM */
  NAV_ITEM_BATCH_ID,
  NAV_ITEM_DEPLOYMENTS,
  NAV_ITEM_OCCURRENCES,
  NAV_ITEM_OVERVIEW,
  NAV_ITEM_SESSIONS,
  NAV_ITEM_SETTINGS,
  NAV_ITEM_SPECIES,

  /* TAB_ITEM */
  TAB_ITEM_GALLERY,
  TAB_ITEM_TABLE,

  /* TABLE_COLUMN */
  TABLE_COLUMN_APPEARANCE,
  TABLE_COLUMN_AVG_TEMP,
  TABLE_COLUMN_DATE,
  TABLE_COLUMN_DEPLOYMENT,
  TABLE_COLUMN_DETECTIONS,
  TABLE_COLUMN_DURATION,
  TABLE_COLUMN_ID,
  TABLE_COLUMN_IMAGES,
  TABLE_COLUMN_MOST_RECENT,
  TABLE_COLUMN_OCCURRENCES,
  TABLE_COLUMN_SESSION,
  TABLE_COLUMN_SESSIONS,
  TABLE_COLUMN_TIME,
  TABLE_COLUMN_SPECIES,
}

const ENGLISH_STRINGS: { [key in STRING]: string } = {
  /* NAV_ITEM */
  [STRING.NAV_ITEM_BATCH_ID]: 'Batch ID',
  [STRING.NAV_ITEM_DEPLOYMENTS]: 'Deployments',
  [STRING.NAV_ITEM_OCCURRENCES]: 'Occurrences',
  [STRING.NAV_ITEM_OVERVIEW]: 'Overview',
  [STRING.NAV_ITEM_SESSIONS]: 'Sessions',
  [STRING.NAV_ITEM_SETTINGS]: 'Settings',
  [STRING.NAV_ITEM_SPECIES]: 'Species',

  /* TAB_ITEM */
  [STRING.TAB_ITEM_GALLERY]: 'Gallery',
  [STRING.TAB_ITEM_TABLE]: 'Table',

  /* TABLE_COLUMN */
  [STRING.TABLE_COLUMN_APPEARANCE]: 'Appearance',
  [STRING.TABLE_COLUMN_AVG_TEMP]: 'Avg temp',
  [STRING.TABLE_COLUMN_DATE]: 'Date',
  [STRING.TABLE_COLUMN_DEPLOYMENT]: 'Deployment',
  [STRING.TABLE_COLUMN_DETECTIONS]: 'Detections',
  [STRING.TABLE_COLUMN_DURATION]: 'Duration',
  [STRING.TABLE_COLUMN_ID]: 'ID',
  [STRING.TABLE_COLUMN_IMAGES]: 'Images',
  [STRING.TABLE_COLUMN_MOST_RECENT]: 'Most recent',
  [STRING.TABLE_COLUMN_OCCURRENCES]: 'Occurrences',
  [STRING.TABLE_COLUMN_SESSION]: 'Session',
  [STRING.TABLE_COLUMN_SESSIONS]: 'Sessions',
  [STRING.TABLE_COLUMN_SPECIES]: 'Species',
  [STRING.TABLE_COLUMN_TIME]: 'Time',
}

// When we have more translations available, this function could return a value based on current language settings.
export const translate = (key: STRING): string => ENGLISH_STRINGS[key]
