# Generated by Django 4.2.2 on 2023-11-10 01:33

import ami.base.schemas
import ami.ml.models.pipeline
from django.db import migrations, models
import django_pydantic_field._migration_serializers
import django_pydantic_field.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("main", "0017_remove_pipeline_algorithms"),
    ]

    operations = [
        migrations.CreateModel(
            name="Algorithm",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("key", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("version", models.IntegerField(default=1)),
                ("version_name", models.CharField(blank=True, max_length=255)),
                ("url", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["name", "version"],
                "unique_together": {("name", "version")},
            },
        ),
        migrations.CreateModel(
            name="Pipeline",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("version", models.IntegerField(default=1)),
                ("version_name", models.CharField(blank=True, max_length=255)),
                (
                    "stages",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        default=ami.base.schemas.default_stages,
                        help_text="The stages of the pipeline. This is mainly for display. The backend implementation of the pipeline may process data in any way.",
                        schema=django_pydantic_field._migration_serializers.GenericContainer(
                            list, (ami.ml.models.pipeline.PipelineStage,)
                        ),
                    ),
                ),
                ("algorithms", models.ManyToManyField(related_name="pipelines", to="ml.algorithm")),
                ("projects", models.ManyToManyField(related_name="pipelines", to="main.project")),
            ],
            options={
                "ordering": ["name", "version"],
                "unique_together": {("name", "version")},
            },
        ),
    ]
