# Generated by Django 4.2.2 on 2023-11-09 23:44

from django.db import migrations


def create_defaults(apps, _schema_editor):
    Algorithm = apps.get_model("ml", "Algorithm")
    Pipeline = apps.get_model("ml", "Pipeline")

    Algorithm.objects.create(
        name="Default",
        description="The default algorithm",
        version="1.0",
        url="",
    )

    Pipeline.objects.create(
        name="Default",
        description="The default pipeline",
        version="1.0",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_defaults, migrations.RunPython.noop),
    ]
