# Generated by Django 4.2.2 on 2023-11-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipeline",
            name="endpoint_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
