# Generated by Django 4.2.2 on 2023-11-09 23:50

import ami.ml.models.pipeline
from django.db import migrations
import django_pydantic_field._migration_serializers
import django_pydantic_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0002_create_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipeline",
            name="stages",
            field=django_pydantic_field.fields.PydanticSchemaField(
                config=None,
                default=[
                    {
                        "key": "default",
                        "name": "Default Stage",
                        "params": [{"key": "default", "name": "Placeholder param", "value": 0}],
                    }
                ],
                schema=django_pydantic_field._migration_serializers.GenericContainer(
                    list, (ami.ml.models.pipeline.PipelineStage,)
                ),
            ),
        ),
    ]
