# Generated by Django 4.2.2 on 2023-11-22 03:03

from django.db import migrations

from django.utils.text import slugify


def populate_pipeline_slugs(apps, schema_editor):
    Pipeline = apps.get_model("ml", "Pipeline")
    for pipeline in Pipeline.objects.all():
        pipeline.slug = slugify(pipeline.name)
        pipeline.save()


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0003_pipeline_slug"),
    ]

    operations = [
        migrations.RunPython(populate_pipeline_slugs, migrations.RunPython.noop),
    ]
