# Generated by Django 4.2.2 on 2023-11-10 00:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0017_remove_pipeline_algorithms_and_more"),
        ("ml", "0003_alter_pipeline_stages"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipeline",
            name="projects",
            field=models.ManyToManyField(related_name="pipelines", to="main.project"),
        ),
    ]
