# Generated by Django 4.2.2 on 2023-11-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0004_populate_pipeline_slugs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipeline",
            name="slug",
            field=models.SlugField(default="2023-11-22 03:07:46.287011", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
