# Generated by Django 4.2.2 on 2023-11-10 00:23

import ami.ml.models.pipeline
from django.db import migrations
import django_pydantic_field._migration_serializers
import django_pydantic_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0004_pipeline_projects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipeline",
            name="stages",
            field=django_pydantic_field.fields.PydanticSchemaField(
                config=None,
                default=ami.ml.models.pipeline.default_stages,
                schema=django_pydantic_field._migration_serializers.GenericContainer(
                    list, (ami.ml.models.pipeline.PipelineStage,)
                ),
            ),
        ),
    ]
