# Generated by Django 4.2.10 on 2024-08-15 03:37

import ami.ml.schemas.v2
from django.db import migrations, models
import django.db.models.deletion
import django_pydantic_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0035_alter_taxon_parents_json_alter_taxon_rank"),
        ("jobs", "0011_alter_job_limit"),
        ("ml", "0005_alter_pipeline_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="PipelineAsyncRequestRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("pipeline_request_id", models.CharField(blank=True, max_length=1024, null=True)),
                ("endpoint_url", models.CharField(max_length=1024)),
                ("token", models.CharField(max_length=1024)),
                (
                    "config_data",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None, schema=ami.ml.schemas.v2.PipelineConfig
                    ),
                ),
                (
                    "response_data",
                    django_pydantic_field.fields.PydanticSchemaField(
                        blank=True, config=None, null=True, schema=ami.ml.schemas.v2.PipelineCallbackResponse
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SENT", "Sent"),
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=32,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pipeline_requests",
                        to="jobs.job",
                    ),
                ),
                ("source_images", models.ManyToManyField(related_name="pipeline_requests", to="main.sourceimage")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
