# Generated by Django 4.2.2 on 2023-11-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0005_alter_pipeline_stages"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="algorithm",
            options={"ordering": ["name", "version"]},
        ),
        migrations.AlterModelOptions(
            name="pipeline",
            options={"ordering": ["name", "version"]},
        ),
        migrations.AddField(
            model_name="algorithm",
            name="version_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="pipeline",
            name="version_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="algorithm",
            name="version",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="pipeline",
            name="version",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name="algorithm",
            unique_together={("name", "version")},
        ),
        migrations.AlterUniqueTogether(
            name="pipeline",
            unique_together={("name", "version")},
        ),
    ]
