# Generated by Django 4.2.10 on 2024-10-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0038_alter_detection_path_alter_sourceimage_event_and_more"),
        ("ml", "0005_alter_pipeline_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipeline",
            name="endpoint_url",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="pipeline",
            name="projects",
            field=models.ManyToManyField(blank=True, related_name="pipelines", to="main.project"),
        ),
    ]
