# Generated by Django 4.2.10 on 2024-08-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0006_pipelineasyncrequestrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipeline",
            name="endpoint_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
