# Generated by Django 4.2.10 on 2024-11-26 18:52

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0006_alter_pipeline_endpoint_url_alter_pipeline_projects"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlgorithmCategoryMap",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("data", models.JSONField()),
                (
                    "labels",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255), default=list, size=None
                    ),
                ),
                ("version", models.CharField(blank=True, max_length=255, null=True)),
                ("url", models.URLField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="algorithm",
            name="category_map",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="algorithms",
                to="ml.algorithmcategorymap",
            ),
        ),
    ]
