# Generated by Django 4.2.10 on 2024-11-03 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0038_alter_detection_path_alter_sourceimage_event_and_more"),
        ("ml", "0006_alter_pipeline_endpoint_url_alter_pipeline_projects"),
    ]

    operations = [
        migrations.CreateModel(
            name="Backend",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("endpoint_url", models.CharField(blank=True, max_length=1024, null=True)),
                ("projects", models.ManyToManyField(blank=True, related_name="backends", to="main.project")),
            ],
            options={
                "verbose_name": "Backend",
                "verbose_name_plural": "Backends",
            },
        ),
    ]
