# Generated by Django 4.2.10 on 2024-11-07 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0007_backend"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pipeline",
            name="endpoint_url",
        ),
        migrations.AddField(
            model_name="pipeline",
            name="backend",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="pipelines", to="ml.backend"
            ),
        ),
    ]
