# Generated by Django 4.2.10 on 2024-12-05 00:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0007_algorithmcategorymap_algorithm_category_map"),
    ]

    operations = [
        migrations.AddField(
            model_name="algorithmcategorymap",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="algorithmcategorymap",
            name="data",
            field=models.JSONField(
                help_text="Complete metadata for each label, such as id, gbif_key, explicit index, source, etc."
            ),
        ),
        migrations.AlterField(
            model_name="algorithmcategorymap",
            name="labels",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                default=list,
                help_text="A simple list of string labels in the correct index order used by the model.",
                size=None,
            ),
        ),
    ]
