# Generated by Django 4.2.10 on 2024-12-05 01:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0008_algorithmcategorymap_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="algorithm",
            name="task_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("detection", "Detection"),
                    ("segmentation", "Segmentation"),
                    ("classification", "Classification"),
                    ("embedding", "Embedding"),
                    ("tracking", "Tracking"),
                    ("tagging", "Tagging"),
                    ("regression", "Regression"),
                    ("captioning", "Captioning"),
                    ("generation", "Generation"),
                    ("translation", "Translation"),
                    ("summarization", "Summarization"),
                    ("question_answering", "Question Answering"),
                    ("depth_estimation", "Depth Estimation"),
                    ("pose_estimation", "Pose Estimation"),
                    ("size_estimation", "Size Estimation"),
                    ("other", "Other"),
                ],
                max_length=255,
            ),
        ),
    ]
