# Generated by Django 4.2.10 on 2024-11-14 19:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0009_remove_pipeline_backend_backend_pipelines"),
    ]

    operations = [
        migrations.AddField(
            model_name="backend",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="backend",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
