# Generated by Django 4.2.10 on 2024-12-05 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0009_algorithm_task_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="algorithm",
            name="version",
            field=models.IntegerField(
                default=1, help_text="An internal, sortable and incrementable version number for the model."
            ),
        ),
    ]
