# Generated by Django 4.2.10 on 2024-11-24 17:56

import ami.base.schemas
from django.db import migrations
import django_pydantic_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0010_backend_created_at_backend_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipeline",
            name="stages",
            field=django_pydantic_field.fields.PydanticSchemaField(
                config=None,
                default=ami.base.schemas.default_stages,
                help_text="The stages of the pipeline. This is mainly for display. The backend implementation of the pipeline may process data in any way.",
                schema="list[PipelineStage]",
            ),
        ),
    ]
