# Generated by Django 4.2.10 on 2024-12-05 04:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0011_alter_algorithm_task_type_alter_algorithm_url_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="algorithm",
            unique_together=set(),
        ),
    ]
