# Generated by Django 4.2.10 on 2024-12-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0011_alter_pipeline_stages"),
    ]

    operations = [
        migrations.AddField(
            model_name="backend",
            name="last_checked",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="backend",
            name="last_checked_live",
            field=models.BooleanField(null=True),
        ),
    ]
