# Generated by Django 4.2.10 on 2024-12-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0012_backend_last_checked_backend_last_checked_live"),
    ]

    operations = [
        migrations.AddField(
            model_name="backend",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="backend",
            name="name",
            field=models.CharField(default="ml_backend", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="backend",
            name="slug",
            field=models.SlugField(default="ml_backend", max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="backend",
            name="version",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="backend",
            name="version_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
