# Generated by Django 4.2.10 on 2024-12-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0012_alter_algorithm_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="algorithm",
            name="url",
        ),
        migrations.RemoveField(
            model_name="algorithmcategorymap",
            name="url",
        ),
        migrations.AddField(
            model_name="algorithm",
            name="uri",
            field=models.CharField(
                blank=True,
                help_text="A URI to the weights or model details. Could be a public web URL or object store path.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="algorithmcategorymap",
            name="labels_hash",
            field=models.BigIntegerField(
                help_text="A hash of the labels for faster comparison of label sets. Created on save.", null=True
            ),
        ),
        migrations.AddField(
            model_name="algorithmcategorymap",
            name="uri",
            field=models.CharField(
                blank=True,
                help_text="A URI to the category map file. Could be a public web URL or object store path.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="algorithmcategorymap",
            name="data",
            field=models.JSONField(
                help_text="Complete metadata for each label, such as id, gbif_key, lookup value, source, etc."
            ),
        ),
    ]
