# Generated by Django 4.2.10 on 2024-12-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0013_backend_description_backend_name_backend_slug_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="backend",
            name="version",
        ),
        migrations.RemoveField(
            model_name="backend",
            name="version_name",
        ),
        migrations.AlterField(
            model_name="backend",
            name="endpoint_url",
            field=models.CharField(default="http://ml_backend:2000", max_length=1024),
            preserve_default=False,
        ),
    ]
