# Generated by Django 4.2.10 on 2024-12-06 21:15

import random
import string
from django.db import migrations


def rename_algorithm_keys(apps, schema_editor):
    """
    The current live ML backend API uses keys with underscores, but the Antenna database
    uses keys with dashes. This migration renames all existing algorithm keys to use underscores
    so that the keys match for new detections.
    """
    Algorithm = apps.get_model("ml", "Algorithm")
    algorithms = Algorithm.objects.all()
    for algorithm in algorithms:
        new_key = algorithm.key.replace("-", "_")
        if Algorithm.objects.filter(key=new_key).exists():
            # Add random 6 char suffix to avoid clashes
            new_key += "_" + "".join(random.choices(string.ascii_lowercase, k=6))
        algorithm.key = new_key
        algorithm.save()


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0013_remove_algorithm_url_remove_algorithmcategorymap_url_and_more"),
    ]

    # Rename all existing algorithm keys to use underscores instead of dashes. Ensure there are no clashes as we go.

    operations = [
        migrations.RunPython(rename_algorithm_keys, reverse_code=migrations.RunPython.noop),
    ]
