# Generated by Django 4.2.10 on 2025-01-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0038_alter_detection_path_alter_sourceimage_event_and_more"),
        ("ml", "0014_remove_backend_version_remove_backend_version_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessingService",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("endpoint_url", models.CharField(max_length=1024)),
                ("last_checked", models.DateTimeField(null=True)),
                ("last_checked_live", models.BooleanField(null=True)),
                (
                    "pipelines",
                    models.ManyToManyField(blank=True, related_name="processing_services", to="ml.pipeline"),
                ),
                (
                    "projects",
                    models.ManyToManyField(blank=True, related_name="processing_services", to="main.project"),
                ),
            ],
            options={
                "verbose_name": "ProcessingService",
                "verbose_name_plural": "ProcessingServices",
            },
        ),
        migrations.DeleteModel(
            name="Backend",
        ),
    ]
