# Generated by Django 4.2.10 on 2025-01-17 21:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0007_add_processing_service"),
        ("ml", "0015_update_existing_intermediate_classifications"),
    ]

    operations = []
