# Generated by Django 4.2.10 on 2025-01-16 20:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0015_processingservice_delete_backend"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="processingservice",
            options={"verbose_name": "Processing Service", "verbose_name_plural": "Processing Services"},
        ),
    ]
