# Generated by Django 4.2.10 on 2025-01-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0016_alter_processingservice_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="processingservice",
            name="slug",
        ),
        migrations.AddField(
            model_name="processingservice",
            name="last_checked_latency",
            field=models.FloatField(null=True),
        ),
    ]
