# Generated by Django 4.2.10 on 2025-03-07 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0058_alter_project_options"),
        ("ml", "0019_projectpipelineconfig_pipeline_new_projects"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectpipelineconfig",
            name="default_parameters",
        ),
        migrations.AddField(
            model_name="projectpipelineconfig",
            name="config",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="projectpipelineconfig",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="projectpipelineconfig",
            name="pipeline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="project_pipeline_configs", to="ml.pipeline"
            ),
        ),
        migrations.AlterField(
            model_name="projectpipelineconfig",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="project_pipeline_configs", to="main.project"
            ),
        ),
    ]
