# Generated by Django 4.2.10 on 2025-03-19 16:27

import ami.ml.schemas
from django.db import migrations
import django_pydantic_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0020_projectpipelineconfig_alter_pipeline_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipeline",
            name="default_config",
            field=django_pydantic_field.fields.PydanticSchemaField(
                config=None,
                default=dict,
                help_text="The default configuration for the pipeline. Used by both the job sending images to the pipeline and the processing service.",
                schema=ami.ml.schemas.PipelineRequestConfigParameters,
            ),
        ),
    ]
