# Generated by Django 4.2.10 on 2025-03-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0020_remove_projectpipelineconfig_default_parameters_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectpipelineconfig",
            name="config",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
