# Generated by Django 4.2.10 on 2025-03-09 17:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0058_alter_project_options"),
        ("ml", "0021_alter_projectpipelineconfig_config"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="projectpipelineconfig",
            unique_together={("pipeline", "project")},
        ),
    ]
