# Generated by Django 4.2.10 on 2026-01-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0025_alter_algorithm_task_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processingservice",
            name="endpoint_url",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
