# Generated by Django 4.2.10 on 2026-03-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0027_rename_last_checked_to_last_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="processingservice",
            name="api_key",
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="processingservice",
            name="api_key_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="processingservice",
            name="api_key_prefix",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="processingservice",
            name="last_seen_client_info",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
