# Generated by Django 4.2.10 on 2026-09-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0028_normalize_empty_endpoint_url_to_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="processingservice",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="Connect new projects to this service automatically. Mark only services run for the whole platform: a project's images are sent to every service it is connected to.",
            ),
        ),
    ]
