# Generated by Django 4.2.10 on 2026-03-29 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0028_normalize_empty_endpoint_url_to_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="processingservice",
            name="last_seen_client_info",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ProcessingServiceAPIKey",
            fields=[
                (
                    "id",
                    models.CharField(editable=False, max_length=150, primary_key=True, serialize=False, unique=True),
                ),
                ("prefix", models.CharField(editable=False, max_length=8, unique=True)),
                ("hashed_key", models.CharField(editable=False, max_length=150)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "name",
                    models.CharField(
                        default="",
                        help_text="A free-form name for the API key. Need not be unique. 50 characters max.",
                        max_length=50,
                    ),
                ),
                (
                    "revoked",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="If the API key is revoked, clients cannot use it anymore. (This cannot be undone.)",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Once API key expires, clients cannot use it anymore.",
                        null=True,
                        verbose_name="Expires",
                    ),
                ),
                (
                    "processing_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="api_keys", to="ml.processingservice"
                    ),
                ),
            ],
            options={
                "verbose_name": "Processing Service API Key",
                "verbose_name_plural": "Processing Service API Keys",
                "ordering": ("-created",),
                "abstract": False,
            },
        ),
    ]
