# Generated by Django 4.2.10 on 2026-09-01 20:26

import django.db.models.deletion
import pgvector.django.halfvec
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0095_grant_sync_deployment_to_mldatamanager"),
        ("ml", "0028_normalize_empty_endpoint_url_to_null"),
    ]

    operations = [
        # Must run before the table is created. makemigrations does not add this, so it
        # is written in by hand. Needs a database user with permission to create an
        # extension; the local compose user is the database owner, so it can.
        VectorExtension(),
        migrations.CreateModel(
            name="DetectionEmbedding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vector",
                    pgvector.django.halfvec.HalfVectorField(dimensions=1024),
                ),
                (
                    "algorithm",
                    models.ForeignKey(
                        help_text="The algorithm whose backbone produced this vector. Vectors from different algorithms live in different spaces and must never be compared to each other.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="ml.algorithm",
                    ),
                ),
                (
                    "detection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="embeddings", to="main.detection"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="detectionembedding",
            constraint=models.UniqueConstraint(
                fields=("detection", "algorithm"), name="unique_embedding_per_detection_and_algorithm"
            ),
        ),
    ]
