# Generated by Django 4.2.10 on 2026-03-27 20:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0029_processingserviceapikey"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="processingservice",
            name="api_key",
        ),
        migrations.RemoveField(
            model_name="processingservice",
            name="api_key_created_at",
        ),
        migrations.RemoveField(
            model_name="processingservice",
            name="api_key_prefix",
        ),
    ]
