# Generated by Django 4.2.10 on 2026-09-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0029_detectionembedding_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="algorithm",
            name="trainable",
            field=models.BooleanField(
                default=False,
                help_text="Whether the processing service reports that this algorithm can be retrained. Mirrored from the service's /info response so the UI does not have to ask it.",
            ),
        ),
    ]
