# Generated by Django 4.2.10 on 2026-10-08 16:04

import ami.ml.schemas
from django.db import migrations, models
import django_pydantic_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0030_detection_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="algorithm",
            name="trainable",
            field=models.BooleanField(
                default=False,
                help_text="Whether the processing service reports that this algorithm can be retrained. Mirrored from the service's /info response so the UI does not have to ask it.",
            ),
        ),
        migrations.AddField(
            model_name="algorithm",
            name="training_config",
            field=django_pydantic_field.fields.PydanticSchemaField(
                blank=True,
                config=None,
                default=ami.ml.schemas.AlgorithmTrainingConfig,
                help_text="Settings used when retraining this algorithm.",
                schema=ami.ml.schemas.AlgorithmTrainingConfig,
            ),
        ),
        migrations.AddField(
            model_name="algorithm",
            name="training_info",
            field=django_pydantic_field.fields.PydanticSchemaField(
                blank=True,
                config=None,
                default=ami.ml.schemas.AlgorithmTrainingInfo,
                help_text="Where this version's weights came from. Empty on a version that was never retrained.",
                schema=ami.ml.schemas.AlgorithmTrainingInfo,
            ),
        ),
    ]
