# Generated by Django 4.2.10 on 2026-09-03 17:05

import ami.ml.schemas
from django.db import migrations
import django_pydantic_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0030_algorithm_trainable"),
    ]

    operations = [
        migrations.AddField(
            model_name="algorithm",
            name="training_config",
            field=django_pydantic_field.fields.PydanticSchemaField(
                blank=True,
                config=None,
                default=ami.ml.schemas.AlgorithmTrainingConfig,
                help_text="Settings used when retraining this algorithm.",
                schema=ami.ml.schemas.AlgorithmTrainingConfig,
            ),
        ),
        migrations.AddField(
            model_name="algorithm",
            name="training_info",
            field=django_pydantic_field.fields.PydanticSchemaField(
                blank=True,
                config=None,
                default=ami.ml.schemas.AlgorithmTrainingInfo,
                help_text="Where this version's weights came from. Empty on a version that was never retrained.",
                schema=ami.ml.schemas.AlgorithmTrainingInfo,
            ),
        ),
    ]
