# Generated by Django 4.2.10 on 2026-09-10 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0095_grant_sync_deployment_to_mldatamanager"),
        ("jobs", "0025_generate_embeddings_job_type"),
        ("ml", "0031_algorithm_training_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingSetMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "algorithm",
                    models.ForeignKey(
                        blank=True,
                        help_text="The algorithm version this occurrence helped produce. Filled in after training finishes, because the version does not exist while the training set is built.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="training_occurrences",
                        to="ml.algorithm",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        help_text="The training job that collected this occurrence.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_set_members",
                        to="jobs.job",
                    ),
                ),
                (
                    "occurrence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="training_uses", to="main.occurrence"
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["occurrence"], name="training_use_occurrence_idx")],
            },
        ),
        migrations.AddConstraint(
            model_name="trainingsetmembership",
            constraint=models.UniqueConstraint(
                fields=("occurrence", "job"), name="unique_training_use_per_occurrence_and_job"
            ),
        ),
    ]
