/* tslint:disable */
/* eslint-disable */
/**
 * Automated Monitoring of Insects ML Platform API
 * Documentation of API endpoints of Automated Monitoring of Insects ML Platform
 *
 * The version of the OpenAPI document: 1.0.0 (api)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

