# Generated by Django 4.2.10 on 2024-09-19 17:54
from django.db import migrations


def lowercase_emails(apps, schema_editor):
    User = apps.get_model("users", "User")
    for user in User.objects.all():
        lowercase_email = user.email.lower()
        if user.email != lowercase_email:
            user.email = lowercase_email
            user.save(update_fields=["email"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_image"),
    ]

    operations = [
        migrations.RunPython(lowercase_emails),
    ]
