# Generated by Django 4.2.10 on 2025-03-16 04:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_lowercase_existing_emails"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="affiliation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
