# Generated by Django 4.2.10 on 2026-01-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_lowercase_existing_emails"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleSchemaVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
