"""Stub out most models

Revision ID: 4d0d5dd8e907
Revises: c9db9afd1258
Create Date: 2023-04-06 00:55:46.310999

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = '4d0d5dd8e907'
down_revision = 'c9db9afd1258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('source_data', sa.String(), nullable=False))
    op.add_column('deployments', sa.Column('location', sa.String(), nullable=False))
    op.add_column('deployments', sa.Column('description', sa.String(), nullable=False))
    op.drop_constraint('occurrences_deployment_id_fkey', 'occurrences', type_='foreignkey')
    op.drop_column('occurrences', 'deployment_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('occurrences', sa.Column('deployment_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('occurrences_deployment_id_fkey', 'occurrences', 'deployments', ['deployment_id'], ['id'])
    op.drop_column('deployments', 'description')
    op.drop_column('deployments', 'location')
    op.drop_column('deployments', 'source_data')
    # ### end Alembic commands ###
