"""Add more fields

Revision ID: 54a2833fbd58
Revises: 809caf1aa4de
Create Date: 2023-04-06 01:52:41.749334

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = '54a2833fbd58'
down_revision = '809caf1aa4de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
