"""Relate events and deployments

Revision ID: 9f2ba7be220c
Revises: 4d0d5dd8e907
Create Date: 2023-04-06 00:57:13.876226

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = '9f2ba7be220c'
down_revision = '4d0d5dd8e907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
