# Generated by Django 4.2.10 on 2025-03-17 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobs", "0024_delete_dataexport"),
        ("main", "0059_merge_20250310_1143"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataExport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("occurrences_simple_json", "occurrences_simple_json"),
                            ("occurrences_simple_csv", "occurrences_simple_csv"),
                        ],
                        max_length=255,
                    ),
                ),
                ("filters", models.JSONField(blank=True, null=True)),
                ("file_url", models.URLField(blank=True, null=True)),
                (
                    "job",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_export",
                        to="jobs.job",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="exports", to="main.project"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
