# Generated by Django 4.2.10 on 2025-04-02 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("main", "0058_alter_project_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataExport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("occurrences_simple_json", "occurrences_simple_json"),
                            ("occurrences_simple_csv", "occurrences_simple_csv"),
                        ],
                        max_length=255,
                    ),
                ),
                ("filters", models.JSONField(blank=True, null=True)),
                ("filters_display", models.JSONField(blank=True, null=True)),
                ("file_url", models.URLField(blank=True, null=True)),
                ("record_count", models.PositiveIntegerField(default=0)),
                ("file_size", models.PositiveBigIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="exports", to="main.project"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
