# Generated by Django 4.2.10 on 2025-03-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataexport",
            name="file_size",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dataexport",
            name="record_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
