# Generated by Django 4.2.10 on 2026-09-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataexport",
            name="format",
            field=models.CharField(
                choices=[
                    ("occurrences_api_json", "occurrences_api_json"),
                    ("occurrences_simple_csv", "occurrences_simple_csv"),
                    ("detections_csv", "detections_csv"),
                ],
                max_length=255,
            ),
        ),
    ]
