# Generated by Django 4.2.10 on 2025-03-30 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exports", "0002_dataexport_file_size_dataexport_record_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataexport",
            name="filters_display",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
