#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python /app/manage.py collectstatic --noinput

exec newrelic-admin run-program /usr/local/bin/gunicorn config.asgi \
    --workers "${WEB_WORKERS:-4}" \
    --bind 0.0.0.0:5000 --chdir=/app -k uvicorn.workers.UvicornWorker
