#!/bin/bash

set -o errexit
set -o nounset


# start the worker with antenna_celeryworker to ensure it's discoverable by ami.ml.signals.get_worker_name
exec watchfiles --filter python celery.__main__.main --args '-A config.celery_app worker --queues=celery -n antenna_celeryworker@%h -l INFO'
