# Generated by Django 4.2.2 on 2023-11-02 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="config",
            field=models.JSONField(
                default={
                    "input": {"name": "N/A", "size": 0},
                    "stages": [
                        {
                            "key": "delay_test",
                            "name": "Delay",
                            "params": [{"key": "delay_seconds", "name": "Delay seconds", "value": 10}],
                        }
                    ],
                },
                null=True,
            ),
        ),
    ]
