# Generated by Django 4.2.2 on 2023-11-02 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0016_pipeline"),
        ("jobs", "0002_alter_job_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="pipeline",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="main.pipeline",
            ),
        ),
    ]
