# Generated by Django 4.2.2 on 2023-11-03 02:46

import ami.jobs.models
from django.db import migrations
import django_pydantic_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0004_job_delay"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="progress",
            field=django_pydantic_field.fields.PydanticSchemaField(
                config=None,
                default={"stages": [], "summary": {"progress": 0.0, "status": "CREATED"}},
                schema=ami.jobs.models.JobProgress,
            ),
        ),
    ]
