# Generated by Django 4.2.2 on 2023-11-05 23:00

import ami.jobs.models
from django.db import migrations, models
import django_pydantic_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0005_alter_job_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="config",
            field=models.JSONField(
                default={
                    "input": {"name": "N/A", "size": 0},
                    "stages": [
                        {
                            "key": "delay",
                            "name": "Delay",
                            "params": [{"key": "delay_seconds", "name": "Delay seconds", "value": "N/A"}],
                        }
                    ],
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="progress",
            field=django_pydantic_field.fields.PydanticSchemaField(
                config=None,
                default={
                    "stages": [],
                    "summary": {"progress": 0.0, "status": "CREATED", "status_label": "Waiting to start"},
                },
                schema=ami.jobs.models.JobProgress,
            ),
        ),
    ]
