# Generated by Django 4.2.2 on 2023-11-08 00:30

import ami.jobs.models
from django.db import migrations, models
import django_pydantic_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0006_alter_job_config_alter_job_progress"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="job",
            name="progress",
            field=django_pydantic_field.fields.PydanticSchemaField(
                config=None,
                default={
                    "errors": [],
                    "logs": [],
                    "stages": [],
                    "summary": {"progress": 0.0, "status": "CREATED", "status_label": "Waiting to start"},
                },
                schema=ami.jobs.models.JobProgress,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "CREATED"),
                    ("PENDING", "PENDING"),
                    ("STARTED", "STARTED"),
                    ("SUCCESS", "SUCCESS"),
                    ("FAILURE", "FAILURE"),
                    ("RETRY", "RETRY"),
                    ("CANCELING", "CANCELING"),
                    ("REVOKED", "REVOKED"),
                    ("RECEIVED", "RECEIVED"),
                    ("UNKNOWN", "UNKNOWN"),
                ],
                default="CREATED",
                max_length=255,
            ),
        ),
    ]
