# Generated by Django 4.2.2 on 2023-11-09 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ml", "0001_initial"),
        ("jobs", "0007_alter_job_options_alter_job_progress_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="pipeline",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="ml.pipeline",
            ),
        ),
    ]
