# Generated by Django 4.2.2 on 2023-11-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0009_remove_job_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="limit",
            field=models.IntegerField(
                blank=True,
                default=100,
                help_text="Limit the number of images to process",
                null=True,
                verbose_name="Limit",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="shuffle",
            field=models.BooleanField(
                default=True, help_text="Process images in a random order", verbose_name="Shuffle"
            ),
        ),
    ]
