# Generated by Django 4.2.10 on 2024-08-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0010_job_limit_job_shuffle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="limit",
            field=models.IntegerField(
                blank=True,
                default=1000,
                help_text="Limit the number of images to process",
                null=True,
                verbose_name="Limit",
            ),
        ),
    ]
