# Generated by Django 4.2.10 on 2024-11-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0011_job_job_type_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="limit",
            field=models.IntegerField(
                blank=True,
                default=None,
                help_text="Limit the number of images to process",
                null=True,
                verbose_name="Limit",
            ),
        ),
    ]
