# Generated by Django 4.2.10 on 2024-12-17 22:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0011_alter_job_limit"),
        ("jobs", "0012_alter_job_limit"),
    ]

    operations = []
