# Generated by Django 4.2.10 on 2025-01-17 21:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0013_merge_0011_alter_job_limit_0012_alter_job_limit"),
        ("jobs", "0014_alter_job_progress"),
    ]

    operations = []
