# Generated by Django 4.2.10 on 2025-03-20 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("exports", "__first__"),
        ("jobs", "0015_merge_20250117_2100"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="data_export",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job",
                to="exports.dataexport",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="params",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_type_key",
            field=models.CharField(
                choices=[
                    ("ml", "ML pipeline"),
                    ("populate_captures_collection", "Populate captures collection"),
                    ("data_storage_sync", "Data storage sync"),
                    ("unknown", "Unknown"),
                    ("data_export", "Data Export"),
                ],
                default="unknown",
                max_length=255,
                verbose_name="Job Type",
            ),
        ),
    ]
