# Generated by Django 4.2.10 on 2025-03-17 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    replaces = [
        ("jobs", "0016_alter_job_job_type_key_dataexporthistory"),
        ("jobs", "0017_dataexport_job_params_delete_dataexporthistory_and_more"),
        ("jobs", "0018_alter_dataexport_format"),
        ("jobs", "0019_dataexport_filters_dataexport_project"),
        ("jobs", "0020_alter_dataexport_job"),
        ("jobs", "0021_remove_dataexport_file_url_remove_dataexport_status_and_more"),
    ]

    dependencies = [
        ("main", "0059_merge_20250310_1143"),
        ("jobs", "0015_merge_20250117_2100"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_type_key",
            field=models.CharField(
                choices=[
                    ("ml", "ML pipeline"),
                    ("populate_captures_collection", "Populate captures collection"),
                    ("data_storage_sync", "Data storage sync"),
                    ("unknown", "Unknown"),
                    ("occurrence_export", "Export Occurrence Data"),
                ],
                default="unknown",
                max_length=255,
                verbose_name="Job Type",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="params",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="DataExport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("occurrences_simple_json", "occurrences_simple_json"),
                            ("occurrences_simple_csv", "occurrences_simple_csv"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "job",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_export",
                        to="jobs.job",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("filters", models.JSONField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to="main.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
