# Generated by Django 4.2.10 on 2025-04-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0015_merge_20250117_2100"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="completed_tasks",
            field=models.IntegerField(default=0, help_text="Number of completed tasks for this job"),
        ),
        migrations.AddField(
            model_name="job",
            name="failed_tasks",
            field=models.IntegerField(default=0, help_text="Number of failed tasks for this job"),
        ),
        migrations.AddField(
            model_name="job",
            name="pending_tasks",
            field=models.IntegerField(default=0, help_text="Number of pending tasks for this job"),
        ),
        migrations.AddField(
            model_name="job",
            name="task_queue_name",
            field=models.CharField(
                blank=True, help_text="Unique queue name for this job's tasks", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="total_tasks",
            field=models.IntegerField(default=0, help_text="Total number of tasks for this job"),
        ),
    ]
