# Generated by Django 4.2.10 on 2025-02-24 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobs", "0015_merge_20250117_2100"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_type_key",
            field=models.CharField(
                choices=[
                    ("ml", "ML pipeline"),
                    ("populate_captures_collection", "Populate captures collection"),
                    ("data_storage_sync", "Data storage sync"),
                    ("unknown", "Unknown"),
                    ("occurrence_export", "Export Occurrence Data"),
                ],
                default="unknown",
                max_length=255,
                verbose_name="Job Type",
            ),
        ),
        migrations.CreateModel(
            name="DataExportHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "CREATED"),
                            ("PENDING", "PENDING"),
                            ("STARTED", "STARTED"),
                            ("SUCCESS", "SUCCESS"),
                            ("FAILURE", "FAILURE"),
                            ("RETRY", "RETRY"),
                            ("CANCELING", "CANCELING"),
                            ("REVOKED", "REVOKED"),
                            ("RECEIVED", "RECEIVED"),
                            ("UNKNOWN", "UNKNOWN"),
                        ],
                        default="CREATED",
                        max_length=255,
                    ),
                ),
                ("file_url", models.URLField(blank=True, null=True)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="export_history", to="jobs.job"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
