# Generated by Django 4.2.10 on 2025-04-18 17:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0016_job_data_export_job_params_alter_job_job_type_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="INFO",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "is_error",
                    models.BooleanField(default=False, help_text="Whether this log should appear in stderr output"),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="log_entries", to="jobs.job"
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["job", "timestamp"], name="jobs_joblog_job_id_695ca3_idx"),
                    models.Index(fields=["job", "is_error"], name="jobs_joblog_job_id_829483_idx"),
                ],
            },
        ),
    ]
