# Generated by Django 4.2.10 on 2025-04-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0016_job_data_export_job_params_alter_job_job_type_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_type_key",
            field=models.CharField(
                choices=[
                    ("ml", "ML pipeline"),
                    ("populate_captures_collection", "Populate captures collection"),
                    ("data_storage_sync", "Data storage sync"),
                    ("unknown", "Unknown"),
                    ("data_export", "Data Export"),
                    ("occurrence_clustering", "Occurrence Feature Clustering"),
                ],
                default="unknown",
                max_length=255,
                verbose_name="Job Type",
            ),
        ),
    ]
