# Generated by Django 4.2.10 on 2025-09-15 21:58

import ami.jobs.models
from django.db import migrations
import django_pydantic_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0016_job_data_export_job_params_alter_job_job_type_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="logs",
            field=django_pydantic_field.fields.PydanticSchemaField(
                config=None, default=ami.jobs.models.JobLogs, schema=ami.jobs.models.JobLogs
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="progress",
            field=django_pydantic_field.fields.PydanticSchemaField(
                config=None, default=ami.jobs.models.default_job_progress, schema=ami.jobs.models.JobProgress
            ),
        ),
    ]
