# Generated by Django 4.2.10 on 2025-03-10 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobs", "0016_alter_job_job_type_key_dataexporthistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataExport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "CREATED"),
                            ("PENDING", "PENDING"),
                            ("STARTED", "STARTED"),
                            ("SUCCESS", "SUCCESS"),
                            ("FAILURE", "FAILURE"),
                            ("RETRY", "RETRY"),
                            ("CANCELING", "CANCELING"),
                            ("REVOKED", "REVOKED"),
                            ("RECEIVED", "RECEIVED"),
                            ("UNKNOWN", "UNKNOWN"),
                        ],
                        default="CREATED",
                        max_length=255,
                    ),
                ),
                ("format", models.CharField(default="json", max_length=255)),
                ("file_url", models.URLField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="job",
            name="params",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="DataExportHistory",
        ),
        migrations.AddField(
            model_name="dataexport",
            name="job",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="data_export", to="jobs.job"
            ),
        ),
        migrations.AddField(
            model_name="dataexport",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="exports", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
