# Generated by Django 4.2.10 on 2025-03-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0017_dataexport_job_params_delete_dataexporthistory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataexport",
            name="format",
            field=models.CharField(
                choices=[
                    ("occurrences_simple_json", "occurrences_simple_json"),
                    ("occurrences_simple_csv", "occurrences_simple_csv"),
                ],
                max_length=255,
            ),
        ),
    ]
