# Generated by Django 4.2.10 on 2026-02-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0018_alter_job_job_type_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="dispatch_mode",
            field=models.CharField(
                choices=[("internal", "Internal"), ("sync_api", "Sync API"), ("async_api", "Async API")],
                default="internal",
                help_text="How the job dispatches its workload: internal, sync_api, or async_api.",
                max_length=32,
            ),
        ),
    ]
