# Generated by Django 4.2.10 on 2026-02-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0018_alter_job_job_type_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="backend",
            field=models.CharField(
                blank=True,
                help_text="The processing service backend that executed this job",
                max_length=255,
                null=True,
            ),
        ),
    ]
