# Generated by Django 4.2.10 on 2025-10-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0018_alter_job_job_type_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="last_checked_at",
            field=models.DateTimeField(
                blank=True, help_text="Last time job status was checked by periodic task", null=True
            ),
        ),
    ]
