# Generated by Django 4.2.10 on 2025-10-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0019_remove_mltaskrecord_subtask_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="last_checked",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
