# Generated by Django 4.2.10 on 2025-09-04 10:42

import ami.jobs.models
from django.db import migrations
import django_pydantic_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0019_mltaskrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="logs",
            field=django_pydantic_field.fields.PydanticSchemaField(
                config=None, default=ami.jobs.models.JobLogs, schema=ami.jobs.models.JobLogs
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="progress",
            field=django_pydantic_field.fields.PydanticSchemaField(
                config=None, default=ami.jobs.models.default_job_progress, schema=ami.jobs.models.JobProgress
            ),
        ),
    ]
