# Generated by Django 4.2.10 on 2025-10-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0020_alter_job_logs_alter_job_progress"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mltaskrecord",
            name="subtask_id",
        ),
        migrations.AlterField(
            model_name="mltaskrecord",
            name="status",
            field=models.CharField(
                choices=[("PENDING", "PENDING"), ("STARTED", "STARTED"), ("SUCCESS", "SUCCESS"), ("FAIL", "FAIL")],
                default="STARTED",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="mltaskrecord",
            name="task_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
