# Generated by Django 4.2.10 on 2025-03-17 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0059_merge_20250310_1143"),
        (
            "jobs",
            "0016_alter_job_job_type_key_dataexporthistory_squashed_0021_remove_dataexport_file_url_remove_dataexport_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataexport",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="exports", to="main.project"
            ),
        ),
    ]
