# Generated by Django 4.2.10 on 2025-03-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0022_alter_dataexport_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataexport",
            name="file_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
