# Generated by Django 4.2.10 on 2025-11-04 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0022_job_last_checked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="last_checked",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name="mltaskrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("STARTED", "STARTED"),
                    ("SUCCESS", "SUCCESS"),
                    ("FAIL", "FAIL"),
                    ("REVOKED", "REVOKED"),
                ],
                default="STARTED",
                max_length=255,
            ),
        ),
    ]
