# Generated by Django 4.2.10 on 2026-04-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0022_alter_job_logs_help_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_type_key",
            field=models.CharField(
                choices=[
                    ("ml", "ML pipeline"),
                    ("populate_captures_collection", "Populate capture set"),
                    ("data_storage_sync", "Data storage sync"),
                    ("unknown", "Unknown"),
                    ("data_export", "Data Export"),
                    ("post_processing", "Post Processing"),
                ],
                default="unknown",
                max_length=255,
                verbose_name="Job Type",
            ),
        ),
    ]
