# Generated by Django 4.2.10 on 2025-03-17 14:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0023_dataexport_file_url"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DataExport",
        ),
    ]
