# Generated by Django 4.2.10 on 2026-09-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0023_alter_job_job_type_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_type_key",
            field=models.CharField(
                choices=[
                    ("ml", "ML pipeline"),
                    ("populate_captures_collection", "Populate capture set"),
                    ("data_storage_sync", "Data storage sync"),
                    ("regroup_events", "Regroup sessions"),
                    ("unknown", "Unknown"),
                    ("data_export", "Data Export"),
                    ("post_processing", "Post Processing"),
                    ("train_classifier", "Train classifier"),
                ],
                default="unknown",
                max_length=255,
                verbose_name="Job Type",
            ),
        ),
    ]
