# Generated by Django 4.2.10 on 2025-03-20 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    replaces = [
        ("jobs", "0024_delete_dataexport"),
        ("jobs", "0025_alter_job_job_type_key"),
        ("jobs", "0026_job_data_export"),
    ]

    dependencies = [
        ("jobs", "0023_dataexport_file_url"),
        ("exports", "0002_remove_dataexport_job"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DataExport",
        ),
        migrations.AlterField(
            model_name="job",
            name="job_type_key",
            field=models.CharField(
                choices=[
                    ("ml", "ML pipeline"),
                    ("populate_captures_collection", "Populate captures collection"),
                    ("data_storage_sync", "Data storage sync"),
                    ("unknown", "Unknown"),
                    ("data_export", "Data Export"),
                ],
                default="unknown",
                max_length=255,
                verbose_name="Job Type",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="data_export",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job",
                to="exports.dataexport",
            ),
        ),
    ]
