# Generated by Django 4.2.10 on 2026-10-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0023_alter_job_job_type_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="hidden",
            field=models.BooleanField(default=False, help_text="Hidden from the job list instead of deleted."),
        ),
    ]
