# Generated by Django 4.2.10 on 2026-09-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0024_train_classifier_job_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_type_key",
            field=models.CharField(
                choices=[
                    ("ml", "ML pipeline"),
                    ("populate_captures_collection", "Populate capture set"),
                    ("data_storage_sync", "Data storage sync"),
                    ("regroup_events", "Regroup sessions"),
                    ("unknown", "Unknown"),
                    ("data_export", "Data Export"),
                    ("post_processing", "Post Processing"),
                    ("train_classifier", "Train classifier"),
                    ("generate_embeddings", "Generate embeddings"),
                ],
                default="unknown",
                max_length=255,
                verbose_name="Job Type",
            ),
        ),
    ]
