# Generated by Django 4.2.2 on 2023-09-15 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LabelStudioConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("project_id", models.PositiveIntegerField(blank=True, null=True)),
                ("access_token", models.CharField(blank=True, max_length=255, null=True)),
                ("base_url", models.CharField(blank=True, max_length=255, null=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("s3_key_id", models.CharField(blank=True, max_length=255, null=True)),
                ("s3_key_secret", models.CharField(blank=True, max_length=255, null=True)),
                ("s3_endpoint", models.CharField(blank=True, max_length=1024, null=True)),
                ("s3_uri", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
