# Generated by Django 4.2.2 on 2023-09-15 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0039_alter_sourceimagecollection_kwargs"),
        ("labelstudio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="labelstudioconfig",
            name="task_collection",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="main.sourceimagecollection"
            ),
        ),
    ]
